"""
Seed data for ByOnco platform
Contains hospital, doctor, and rare cancer data for 31 cities worldwide
"""

# 31 cities worldwide for top oncology treatment
CITIES = [
    # India (7 cities)
    "Mumbai", "New Delhi", "Chennai", "Bengaluru", "Hyderabad", "Pune", "Nashik",
    # USA (6 cities)
    "New York City", "Boston", "Houston", "Rochester (MN)", "Los Angeles", "Philadelphia", "Baltimore",
    # Asia-Pacific (3 cities)
    "Singapore", "Tokyo", "Osaka",
    # Middle East & Europe (15 cities)
    "Istanbul", "Ankara", "Toronto", "Vancouver", "Berlin", "Heidelberg", "Abu Dhabi", "Dubai",
    "Oslo", "London", "Manchester", "Paris", "Lyon", "Bangkok"
]

# Rare and Ultra-Rare Cancer Types
RARE_CANCERS = [
    # Ultra-Rare and Most Clinically Challenging
    {"name": "Diffuse Intrinsic Pontine Glioma (DIPG)", "category": "ultra-rare", "type": "Pediatric Brain Tumor"},
    {"name": "Atypical Teratoid Rhabdoid Tumor (ATRT)", "category": "ultra-rare", "type": "Pediatric Brain Tumor"},
    {"name": "Embryonal Tumor with Multilayered Rosettes (ETMR)", "category": "ultra-rare", "type": "Pediatric Brain Tumor"},
    {"name": "Midline NUT Carcinoma", "category": "ultra-rare", "type": "Rare Carcinoma"},
    {"name": "Small Cell Carcinoma of the Ovary, Hypercalcemic Type (SCCOHT)", "category": "ultra-rare", "type": "Ovarian Cancer"},
    {"name": "Anaplastic Thyroid Carcinoma (ATC)", "category": "ultra-rare", "type": "Thyroid Cancer"},
    {"name": "Desmoplastic Small Round Cell Tumor (DSRCT)", "category": "ultra-rare", "type": "Sarcoma"},
    {"name": "Epithelioid Hemangioendothelioma (EHE)", "category": "ultra-rare", "type": "Vascular Tumor"},
    {"name": "Histiocytic Sarcoma", "category": "ultra-rare", "type": "Sarcoma"},
    {"name": "Erdheim-Chester Disease (ECD)", "category": "ultra-rare", "type": "Histiocytic Disorder"},
    {"name": "Blastic Plasmacytoid Dendritic Cell Neoplasm (BPDCN)", "category": "ultra-rare", "type": "Leukemia/Lymphoma"},
    {"name": "T-cell Prolymphocytic Leukemia (T-PLL)", "category": "ultra-rare", "type": "Leukemia"},
    {"name": "Hepatosplenic T-cell Lymphoma (HSTCL)", "category": "ultra-rare", "type": "Lymphoma"},
    {"name": "Malignant Rhabdoid Tumor", "category": "ultra-rare", "type": "Pediatric Tumor"},
    
    # Very Rare and High-Risk
    {"name": "Alveolar Soft Part Sarcoma (ASPS)", "category": "very-rare", "type": "Sarcoma"},
    {"name": "Clear Cell Sarcoma", "category": "very-rare", "type": "Sarcoma"},
    {"name": "Angiosarcoma", "category": "very-rare", "type": "Sarcoma"},
    {"name": "Chordoma", "category": "very-rare", "type": "Bone Tumor"},
    {"name": "Adrenocortical Carcinoma (ACC)", "category": "very-rare", "type": "Adrenal Cancer"},
    {"name": "Merkel Cell Carcinoma", "category": "very-rare", "type": "Skin Cancer"},
    {"name": "Uveal Melanoma", "category": "very-rare", "type": "Eye Cancer"},
    {"name": "Fibrolamellar Hepatocellular Carcinoma (FL-HCC)", "category": "very-rare", "type": "Liver Cancer"},
    {"name": "Adenoid Cystic Carcinoma (ACC)", "category": "very-rare", "type": "Salivary Gland Cancer"},
    {"name": "Esthesioneuroblastoma", "category": "very-rare", "type": "Nasal Cavity Cancer"},
    {"name": "Appendiceal Carcinoma", "category": "very-rare", "type": "GI Cancer"},
    {"name": "Angioimmunoblastic T-cell Lymphoma (AITL)", "category": "very-rare", "type": "Lymphoma"},
    
    # Rare but Moderately Complex
    {"name": "Cholangiocarcinoma", "category": "rare", "type": "Bile Duct Cancer"},
    {"name": "Gestational Trophoblastic Neoplasia", "category": "rare", "type": "Pregnancy-related"},
    {"name": "Thymic Carcinoma", "category": "rare", "type": "Mediastinal Tumor"},
    {"name": "Gastrointestinal Stromal Tumor (GIST)", "category": "rare", "type": "GI Cancer"},
    {"name": "Pancreatic Neuroendocrine Tumors (pNETs)", "category": "rare", "type": "Pancreatic Cancer"},
    {"name": "Penile Squamous Cell Carcinoma", "category": "rare", "type": "Genitourinary"},
    {"name": "Vulvar Cancer", "category": "rare", "type": "Gynecologic"},
    {"name": "Vaginal Cancer", "category": "rare", "type": "Gynecologic"},
    {"name": "Osteosarcoma", "category": "rare", "type": "Bone Cancer"},
    {"name": "Ewing Sarcoma", "category": "rare", "type": "Bone/Soft Tissue"},
    {"name": "Retinoblastoma", "category": "rare", "type": "Eye Cancer"},
    {"name": "Malignant Mesothelioma", "category": "rare", "type": "Pleural Tumor"},
    {"name": "Cancer of Unknown Primary (CUP)", "category": "rare", "type": "Unknown Primary"},
]

# Common cancers (Tier 1 & 2)
COMMON_CANCERS = [
    {"name": "Breast Cancer", "category": "common", "type": "Breast"},
    {"name": "Lung Cancer", "category": "common", "type": "Lung"},
    {"name": "Colorectal Cancer", "category": "common", "type": "GI"},
    {"name": "Prostate Cancer", "category": "common", "type": "Genitourinary"},
    {"name": "Cervical Cancer", "category": "common", "type": "Gynecologic"},
    {"name": "Liver Cancer (HCC)", "category": "common", "type": "Liver"},
    {"name": "Gastric Cancer", "category": "common", "type": "GI"},
    {"name": "Bladder Cancer", "category": "common", "type": "Genitourinary"},
    {"name": "Uterine Cancer", "category": "common", "type": "Gynecologic"},
    {"name": "Non-Hodgkin Lymphoma", "category": "common", "type": "Lymphoma"},
    {"name": "Kidney Cancer", "category": "less-common", "type": "Genitourinary"},
    {"name": "Ovarian Cancer", "category": "less-common", "type": "Gynecologic"},
    {"name": "Thyroid Cancer", "category": "less-common", "type": "Thyroid"},
    {"name": "Esophageal Cancer", "category": "less-common", "type": "GI"},
    {"name": "Hodgkin Lymphoma", "category": "less-common", "type": "Lymphoma"},
    {"name": "Multiple Myeloma", "category": "less-common", "type": "Blood Cancer"},
    {"name": "Brain Tumors (High-Grade Gliomas)", "category": "less-common", "type": "Brain"},
    {"name": "Testicular Cancer", "category": "less-common", "type": "Genitourinary"},
    {"name": "Oral Cancer", "category": "less-common", "type": "Head & Neck"},
    {"name": "Melanoma", "category": "less-common", "type": "Skin"},
]

ALL_CANCERS = RARE_CANCERS + COMMON_CANCERS

# Hospital data for each city
HOSPITALS = {
    "Mumbai": [
        {
            "id": "tmc-mumbai",
            "name": "Tata Memorial Hospital",
            "city": "Mumbai",
            "address": "Dr. Ernest Borges Road, Parel, Mumbai – 400012",
            "established_year": 1941,
            "tier": "Tier 1",
            "accreditation": "NABL-accredited laboratories",
            "specializations": ["All Cancer Types", "Pediatric Oncology", "Surgical Oncology", "Medical Oncology", "Radiation Therapy", "Bone Marrow Transplant", "Proton Therapy", "DIPG", "ATRT", "ETMR", "Rare Sarcomas", "Hematologic Oncology"],
            "success_rate": 94,
            "wait_time_days": 3,
            "beds_available": 12,
            "total_beds": 450,
            "treatments": ["Surgery", "Chemotherapy", "Radiation", "Immunotherapy", "CAR-T Therapy", "Proton Therapy", "Bone Marrow Transplant"],
            "cost_range": {"min": 500000, "max": 2500000},
            "accepts_insurance": True,
            "insurance_types": ["Mediclaim", "CGHS", "ESIC", "Ayushman Bharat"],
            "international_patients": True,
            "languages": ["English", "Hindi", "Marathi"],
            "rating": 4.8,
            "reviews_count": 2500,
            "image_url": "https://doctorlistingingestionpr.blob.core.windows.net/doctorprofilepic/1671606334081_HospitalProfileImage_Capture.PNG",
            "imageUrl": "https://doctorlistingingestionpr.blob.core.windows.net/doctorprofilepic/1671606334081_HospitalProfileImage_Capture.PNG",
            "detailsUrl": "https://tmc.gov.in/abha",
            "appointmentUrl": "https://tmc.gov.in/abha",
            "phone": "+91 (22)2740 5085",
            "contactEmail": "mail@actrec.gov.in",
            "inquiryUrl": None
        },
        {
            "id": "kdah-mumbai",
            "name": "Kokilaben Dhirubhai Ambani Hospital & Medical Research Institute",
            "city": "Mumbai",
            "address": "Achutrao Patwardhan Marg, Four Bungalows, Andheri West, Mumbai",
            "established_year": 2009,
            "tier": "Tier 2",
            "accreditation": "JCI-accredited, NABH accredited",
            "specializations": ["Breast Cancer", "Head & Neck Cancer", "Neuro-oncology", "GI Cancers", "Bone Marrow Transplant", "Common Cancers", "Rare Cancers", "Merkel Cell Carcinoma", "Chordoma", "FL-HCC"],
            "success_rate": 92,
            "wait_time_days": 4,
            "beds_available": 10,
            "total_beds": 180,
            "treatments": ["Surgery", "Chemotherapy", "Radiation", "Immunotherapy", "Robotic Surgery", "IMRT/IGRT", "Stereotactic Radiosurgery", "Bone Marrow Transplant"],
            "cost_range": {"min": 1000000, "max": 3500000},
            "accepts_insurance": True,
            "insurance_types": ["Mediclaim", "HDFC Ergo", "ICICI Lombard", "Private Insurance"],
            "international_patients": True,
            "languages": ["English", "Hindi", "Marathi"],
            "rating": 4.7,
            "reviews_count": 1800,
            "image_url": "https://static.wixstatic.com/media/0ccbd3_88737cce70b04e1babcbd803265ba277~mv2.jpeg/v1/fill/w_560,h_400,al_c,q_80,usm_0.66_1.00_0.01,enc_auto/0ccbd3_88737cce70b04e1babcbd803265ba277~mv2.jpeg",
            "imageUrl": "https://static.wixstatic.com/media/0ccbd3_88737cce70b04e1babcbd803265ba277~mv2.jpeg/v1/fill/w_560,h_400,al_c,q_80,usm_0.66_1.00_0.01,enc_auto/0ccbd3_88737cce70b04e1babcbd803265ba277~mv2.jpeg",
            "detailsUrl": "https://www.kokilabenhospital.com/contacts/enquires.html",
            "appointmentUrl": "https://online.kokilabenhospital.com/online-consultation",
            "phone": "+91 (22) 4269 6969",
            "contactEmail": None,
            "inquiryUrl": "https://www.kokilabenhospital.com/contacts/enquires.html"
        },
        {
            "id": "jaslok-mumbai",
            "name": "Jaslok Hospital & Research Centre",
            "city": "Mumbai",
            "address": "15, Dr. G. Deshmukh Marg (Pedder Road), Near Mahalakshmi Temple, Mumbai",
            "established_year": 1970,
            "tier": "Tier 2",
            "accreditation": "NABH accredited, ISO certified",
            "specializations": ["Surgical Oncology", "Medical Oncology", "Radiation Oncology", "Bone Marrow Transplant", "Nuclear Medicine", "Brain Tumors", "Spine Tumors", "Common Cancers", "Rare Cancers"],
            "success_rate": 91,
            "wait_time_days": 5,
            "beds_available": 8,
            "total_beds": 200,
            "treatments": ["Surgery", "Chemotherapy", "Radiation", "CyberKnife", "TrueBeam", "Bone Marrow Transplant", "Palliative Care"],
            "cost_range": {"min": 800000, "max": 3000000},
            "accepts_insurance": True,
            "insurance_types": ["Mediclaim", "Star Health", "Max Bupa", "Private Insurance"],
            "international_patients": True,
            "languages": ["English", "Hindi", "Marathi", "Gujarati"],
            "rating": 4.6,
            "reviews_count": 1500,
            "image_url": "https://lh3.googleusercontent.com/gps-cs-s/AG0ilSwI7suZ4PI5MU7X_Cry0t25GEj8wmqth-eXkB5Zzsw38yXUpXjR7r5FhRS2SI-bKxwylyDISrE7XnfgEkcfx6yutRsV7YeEZ2OrQDMczcjbQLoW-zphTHaBYQc3f7B8w1_C6jU=s1360-w1360-h1020",
            "imageUrl": "https://lh3.googleusercontent.com/gps-cs-s/AG0ilSwI7suZ4PI5MU7X_Cry0t25GEj8wmqth-eXkB5Zzsw38yXUpXjR7r5FhRS2SI-bKxwylyDISrE7XnfgEkcfx6yutRsV7YeEZ2OrQDMczcjbQLoW-zphTHaBYQc3f7B8w1_C6jU=s1360-w1360-h1020",
            "detailsUrl": "https://jaslokconnect1.jaslokhospital.net:4434/Appointment/",
            "appointmentUrl": "https://jaslokconnect1.jaslokhospital.net:4434/Appointment/",
            "phone": "99201 66688",
            "contactEmail": "info@jaslokhospital.net, appointments@jaslokhospital.net",
            "inquiryUrl": None
        },
        {
            "id": "fortis-mulund-mumbai",
            "name": "Fortis Hospital, Mulund",
            "city": "Mumbai",
            "address": "Mulund Goregaon Link Road, Mulund West, Mumbai",
            "established_year": 2002,
            "tier": "Tier 2",
            "accreditation": "JCI, NABH, NABL accredited",
            "specializations": ["Surgical Oncology", "Medical Oncology", "Bone Marrow Transplant", "HIPEC", "Common Cancers", "Rare Cancers", "Pediatric Cancers", "Sarcomas"],
            "success_rate": 90,
            "wait_time_days": 6,
            "beds_available": 7,
            "total_beds": 220,
            "treatments": ["Surgery", "Chemotherapy", "Radiation", "Immunotherapy", "Targeted Therapy", "Bone Marrow Transplant", "HIPEC"],
            "cost_range": {"min": 700000, "max": 3200000},
            "accepts_insurance": True,
            "insurance_types": ["Mediclaim", "Star Health", "Max Bupa", "Private Insurance"],
            "international_patients": True,
            "languages": ["English", "Hindi", "Marathi"],
            "rating": 4.6,
            "reviews_count": 1400,
            "image_url": "https://www.kareoptions.com/healthtourism/img/background/8c600df8-92f5-4f23-b932-e7bd88c380c5_h_fortis_mulund_4.jpg",
            "imageUrl": "https://www.kareoptions.com/healthtourism/img/background/8c600df8-92f5-4f23-b932-e7bd88c380c5_h_fortis_mulund_4.jpg",
            "detailsUrl": "https://www.fortishealthcare.com/doctors?location=all",
            "appointmentUrl": "https://www.fortishealthcare.com/doctors?location=all",
            "phone": "+91-9205-010-100",
            "contactEmail": "reachus@fortishealthcare.com"
        },
    ],
    "New Delhi": [
        {
            "id": "aiims-delhi",
            "name": "All India Institute of Medical Sciences (AIIMS), New Delhi – Dr. B.R.A. IRCH",
            "city": "New Delhi",
            "address": "AIIMS Campus, Ansari Nagar, New Delhi – 110029",
            "established_year": 1983,
            "tier": "Tier 1",
            "accreditation": "NABL accredited laboratories",
            "specializations": ["All Cancer Types", "Pediatric Oncology", "Surgical Oncology", "Medical Oncology", "Radiation Oncology", "Bone Marrow Transplant", "Research Trials", "DIPG", "ATRT", "Retinoblastoma", "CUP"],
            "success_rate": 94,
            "wait_time_days": 10,
            "beds_available": 5,
            "total_beds": 500,
            "treatments": ["Surgery", "Chemotherapy", "Radiation", "Immunotherapy", "Clinical Trials", "Bone Marrow Transplant", "Trilogy Linear Accelerators"],
            "cost_range": {"min": 200000, "max": 1500000},
            "accepts_insurance": True,
            "insurance_types": ["CGHS", "ESIC", "Ayushman Bharat"],
            "international_patients": False,
            "languages": ["English", "Hindi"],
            "rating": 4.8,
            "reviews_count": 4000,
            "image_url": "https://w0.peakpx.com/wallpaper/261/790/HD-wallpaper-aiims-all-india-institute-of-medical-sciences-new-delhi.jpg",
            "imageUrl": "https://w0.peakpx.com/wallpaper/261/790/HD-wallpaper-aiims-all-india-institute-of-medical-sciences-new-delhi.jpg",
            "detailsUrl": "https://ors.gov.in/orsportal/",
            "phone": "+91-11-26588500",
            "contactEmail": "ms.main@aiims.gov.in"
        },
        {
            "id": "rgcirc-delhi",
            "name": "Rajiv Gandhi Cancer Institute & Research Centre (RGCIRC)",
            "city": "New Delhi",
            "address": "Rohini, Sector 5, New Delhi – 110085",
            "established_year": 1996,
            "tier": "Tier 1",
            "accreditation": "NABH accredited, NABL certified",
            "specializations": ["Breast Cancer", "Lung Cancer", "Liver Cancer", "Bone Marrow Transplant", "Tomotherapy", "CyberKnife", "HIPEC", "Common Cancers", "Rare Cancers", "Pediatric Cancers", "Sarcomas"],
            "success_rate": 93,
            "wait_time_days": 4,
            "beds_available": 14,
            "total_beds": 300,
            "treatments": ["Surgery", "Chemotherapy", "Radiation", "Immunotherapy", "Bone Marrow Transplant", "Tomotherapy", "CyberKnife", "HIPEC", "Robotic Surgery"],
            "cost_range": {"min": 600000, "max": 2800000},
            "accepts_insurance": True,
            "insurance_types": ["Mediclaim", "CGHS", "Star Health", "Private Insurance"],
            "international_patients": True,
            "languages": ["English", "Hindi", "Punjabi"],
            "rating": 4.7,
            "reviews_count": 2800,
            "image_url": "https://www.foxchase.org/sites/default/files/pr-4.jpg",
            "imageUrl": "https://www.foxchase.org/sites/default/files/pr-4.jpg",
            "detailsUrl": "https://care.rgcirc.org/",
            "phone": "+91-11-47022222",
            "contactEmail": "info@rgcirc.org"
        },
        {
            "id": "apollo-delhi",
            "name": "Indraprastha Apollo Hospital, Delhi – Apollo Cancer Centre",
            "city": "New Delhi",
            "address": "Mathura Road, Sarita Vihar, New Delhi – 110076",
            "established_year": 1996,
            "tier": "Tier 2",
            "accreditation": "JCI accredited, NABH accredited, NABL accredited",
            "specializations": ["Breast Cancer", "Liver Cancer", "Blood Cancers", "Pediatric Cancers", "Robotic Surgery", "PET-MRI", "Common Cancers", "Rare Cancers", "GIST", "Gestational Trophoblastic Tumors"],
            "success_rate": 92,
            "wait_time_days": 5,
            "beds_available": 11,
            "total_beds": 280,
            "treatments": ["Surgery", "Chemotherapy", "Radiation", "Robotic Surgery", "Bone Marrow Transplant", "Immunotherapy", "Targeted Therapy"],
            "cost_range": {"min": 900000, "max": 3500000},
            "accepts_insurance": True,
            "insurance_types": ["Mediclaim", "Max Bupa", "HDFC Ergo", "Private Insurance"],
            "international_patients": True,
            "languages": ["English", "Hindi"],
            "rating": 4.7,
            "reviews_count": 2200,
            "image_url": "https://static.medigence.com/uploads/hospital/images/1743572330_ee6772310d4b579ccdc4.jpg",
            "imageUrl": "https://static.medigence.com/uploads/hospital/images/1743572330_ee6772310d4b579ccdc4.jpg",
            "detailsUrl": "https://www.apollohospitals.com/doctors?f%5B0%5D=speciality%3A196&f%5B1%5D=speciality%3A94&f%5B2%5D=speciality%3A124&f%5B3%5D=speciality%3A131&f%5B4%5D=speciality%3A503&f%5B5%5D=speciality%3A519&f%5B6%5D=speciality%3A567&f%5B7%5D=speciality%3A3277&f%5B8%5D=speciality%3A3325&f%5B9%5D=speciality%3A3419&f%5B10%5D=speciality%3A3787&f%5B11%5D=speciality%3A3791&f%5B12%5D=speciality%3A4064&f%5B13%5D=speciality%3A4389&f%5B14%5D=speciality%3A7962&f%5B15%5D=speciality%3A8007&f%5B16%5D=speciality%3A8069&f%5B17%5D=speciality%3A8228&f%5B18%5D=speciality%3A8238&f%5B19%5D=speciality%3A8256&f%5B20%5D=speciality%3A8263&f%5B21%5D=speciality%3A8265&f%5B22%5D=speciality%3A8268&f%5B23%5D=speciality%3A8271&f%5B24%5D=speciality%3A8273&f%5B25%5D=speciality%3A8276&f%5B26%5D=speciality%3A8281&f%5B27%5D=speciality%3A8285&f%5B28%5D=speciality%3A8304&f%5B29%5D=speciality%3A8331&f%5B30%5D=speciality%3A8332&f%5B31%5D=speciality%3A8333&f%5B32%5D=speciality%3A8334&f%5B33%5D=speciality%3A8335&f%5B34%5D=speciality%3A8336&f%5B35%5D=speciality%3A8337&f%5B36%5D=speciality%3A8338&f%5B37%5D=speciality%3A8339&f%5B38%5D=speciality%3A8340&f%5B39%5D=speciality%3A8341&f%5B40%5D=speciality%3A8342&f%5B41%5D=speciality%3A8343&f%5B42%5D=speciality%3A11666&f%5B43%5D=speciality%3A11699&f%5B44%5D=speciality%3A11704&f%5B45%5D=speciality%3A12753",
            "phone": "+91-11-26925858",
            "contactEmail": "imcl@apollohospitals.com"
        },
        {
            "id": "dharamshila-delhi",
            "name": "Dharamshila Narayana Superspeciality Hospital",
            "city": "New Delhi",
            "address": "Vasundhara Enclave, Delhi – 110096",
            "established_year": 1994,
            "tier": "Tier 2",
            "accreditation": "NABH accredited",
            "specializations": ["Head-Neck Cancer", "Breast Cancer", "Thoracic Oncology", "GI Oncology", "Uro-oncology", "Bone Marrow Transplant", "Common Cancers", "Rare Cancers", "Sarcomas", "Pediatric Cancers"],
            "success_rate": 91,
            "wait_time_days": 6,
            "beds_available": 9,
            "total_beds": 200,
            "treatments": ["Surgery", "Chemotherapy", "Radiation", "IMRT", "IGRT", "VMAT", "Bone Marrow Transplant", "High-dose Radio-iodine Therapy"],
            "cost_range": {"min": 700000, "max": 3000000},
            "accepts_insurance": True,
            "insurance_types": ["Mediclaim", "CGHS", "Private Insurance"],
            "international_patients": True,
            "languages": ["English", "Hindi"],
            "rating": 4.6,
            "reviews_count": 1800,
            "image_url": "https://images.jdmagicbox.com/v2/comp/delhi/52/011pf025452/catalogue/dharamshila-narayana-superspeciality-hospital-vasundhara-enclave-delhi-private-hospitals-3wuhd.jpg",
            "imageUrl": "https://images.jdmagicbox.com/v2/comp/delhi/52/011pf025452/catalogue/dharamshila-narayana-superspeciality-hospital-vasundhara-enclave-delhi-private-hospitals-3wuhd.jpg",
            "detailsUrl": "https://www.narayanahealth.org/appointment",
            "appointmentUrl": "https://www.narayanahealth.org/appointment",
            "phone": "+91-1800-309-0309",
            "contactEmail": "info.dnsh@narayanahealth.org"
        }
    ],
    "Bengaluru": [
        {
            "id": "kidwai-bengaluru",
            "name": "Kidwai Memorial Institute of Oncology (KMIO)",
            "city": "Bengaluru",
            "address": "Dr. M.H. Marigowda Road, Hombegowda Nagar, Bangalore, Karnataka – 560029",
            "established_year": 1973,
            "tier": "Tier 1",
            "accreditation": "Autonomous under Govt. of Karnataka, WHO (UICC member)",
            "specializations": ["Surgical Oncology", "Radiation Oncology", "Medical Oncology", "Pediatric Oncology", "Head-Neck Cancers", "Breast Cancer", "Cervical Cancer", "Common Cancers", "Rare Cancers", "Bone Marrow Transplant"],
            "success_rate": 93,
            "wait_time_days": 4,
            "beds_available": 15,
            "total_beds": 300,
            "treatments": ["Surgery", "Chemotherapy", "Radiation", "Bone Marrow Transplant", "Nuclear Medicine", "Cobalt Therapy"],
            "cost_range": {"min": 400000, "max": 2000000},
            "accepts_insurance": True,
            "insurance_types": ["CGHS", "ESIC", "Ayushman Bharat"],
            "international_patients": True,
            "languages": ["English", "Hindi", "Kannada", "Tamil"],
            "rating": 4.8,
            "reviews_count": 2500,
            "image_url": "https://medicaldialogues.in/h-upload/2025/01/25/270976-kidwai-memorial-institute-of-oncology.jpg",
            "imageUrl": "https://medicaldialogues.in/h-upload/2025/01/25/270976-kidwai-memorial-institute-of-oncology.jpg",
            "detailsUrl": "https://kmio.karnataka.gov.in/11/register-as-new-patient/en",
            "phone": "+91-80-66697999",
            "contactEmail": "drramachandrac18@gmail.com"
        },
        {
            "id": "hcg-bengaluru",
            "name": "HealthCare Global (HCG) Cancer Centre, Bangalore",
            "city": "Bengaluru",
            "address": "#8, P.Kalinga Rao Road, Sampangi Ram Nagar, Bengaluru, Karnataka – 560027",
            "established_year": 1989,
            "tier": "Tier 2",
            "accreditation": "NABH, NABL, DSIR, FDA, CAP, ISO 9001",
            "specializations": ["Breast Cancer", "Head & Neck Cancer", "GI Oncology", "Musculoskeletal Oncology", "CyberKnife", "Common Cancers", "Rare Cancers", "Ocular Melanomas", "Sarcomas", "Pediatric Cancers", "Brain Tumors"],
            "success_rate": 93,
            "wait_time_days": 4,
            "beds_available": 15,
            "total_beds": 300,
            "treatments": ["Surgery", "Chemotherapy", "Radiation", "CyberKnife", "Tomotherapy", "Targeted Radionuclide Therapy", "Precision Oncology"],
            "cost_range": {"min": 600000, "max": 2800000},
            "accepts_insurance": True,
            "insurance_types": ["Mediclaim", "CGHS", "Private Insurance", "Ayushman Bharat"],
            "international_patients": True,
            "languages": ["English", "Hindi", "Kannada", "Tamil"],
            "rating": 4.8,
            "reviews_count": 2200,
            "image_url": "https://static.medigence.com/uploads/hospital/images/1743572330_ee6772310d4b579ccdc4.jpg",
            "imageUrl": "https://static.medigence.com/uploads/hospital/images/1743572330_ee6772310d4b579ccdc4.jpg",
            "detailsUrl": "https://www.hcgoncology.com/contact-us/",
            "phone": "+91-7406-4999-99",
            "contactEmail": "query@hcgel.com"
        },
        {
            "id": "mazumdar-bengaluru",
            "name": "Mazumdar Shaw Medical Center (Narayana Health City, Bangalore)",
            "city": "Bengaluru",
            "address": "Narayana Health City, Bommasandra, Hosur Road, Bangalore, Karnataka – 560099",
            "established_year": 2009,
            "tier": "Tier 1",
            "accreditation": "JCI accredited, NABH accredited",
            "specializations": ["All Cancer Types", "Pediatric Oncology", "Surgical Oncology", "Medical Oncology", "Radiation Oncology", "Bone Marrow Transplant", "Neuro-oncology", "Musculoskeletal Oncology", "HIPEC", "Common Cancers", "Rare Cancers", "Ultra-Rare Cancers"],
            "success_rate": 95,
            "wait_time_days": 3,
            "beds_available": 20,
            "total_beds": 500,
            "treatments": ["Surgery", "Chemotherapy", "Radiation", "Bone Marrow Transplant", "Robotic Surgery", "HIPEC", "IMRT/VMAT", "Precision Oncology", "Clinical Trials"],
            "cost_range": {"min": 500000, "max": 2500000},
            "accepts_insurance": True,
            "insurance_types": ["Mediclaim", "CGHS", "Private Insurance", "Ayushman Bharat"],
            "international_patients": True,
            "languages": ["English", "Hindi", "Kannada", "Tamil"],
            "rating": 4.9,
            "reviews_count": 3000,
            "image_url": "https://images1-fabric.practo.com/mazumdar-shaw-medical-center-bangalore-1468319443-5784c6d343789.jpg",
            "imageUrl": "https://images1-fabric.practo.com/mazumdar-shaw-medical-center-bangalore-1468319443-5784c6d343789.jpg",
            "detailsUrl": "https://www.narayanahealth.org/appointment",
            "appointmentUrl": "https://www.narayanahealth.org/appointment",
            "phone": "+91-1800-309-0309",
            "contactEmail": "info.msmc@narayanahealth.org"
        }
    ],
    "Chennai": [
        {
            "id": "cancer-institute-chennai",
            "name": "Cancer Institute (WIA), Adyar, Chennai",
            "city": "Chennai",
            "address": "38, Sardar Patel Road, Adyar, Chennai, Tamil Nadu – 600036",
            "established_year": 1954,
            "tier": "Tier 1",
            "accreditation": "Regional Cancer Centre, WHO supported",
            "specializations": ["Surgical Oncology", "Medical Oncology", "Radiation Oncology", "Pediatric Oncology", "Gynecologic Oncology", "Oral Cancer", "Breast Cancer", "Cervical Cancer", "Common Cancers", "Rare Cancers", "Retinoblastoma", "Choriocarcinoma"],
            "success_rate": 92,
            "wait_time_days": 4,
            "beds_available": 12,
            "total_beds": 250,
            "treatments": ["Surgery", "Chemotherapy", "Radiation", "Brachytherapy", "Bone Marrow Transplant", "Limb-sparing Surgeries"],
            "cost_range": {"min": 400000, "max": 2000000},
            "accepts_insurance": True,
            "insurance_types": ["Mediclaim", "CGHS", "Ayushman Bharat"],
            "international_patients": True,
            "languages": ["English", "Tamil", "Hindi"],
            "rating": 4.7,
            "reviews_count": 2100,
            "image_url": "https://rawahealth.com/wp-content/uploads/2024/10/poip.jpg",
            "imageUrl": "https://rawahealth.com/wp-content/uploads/2024/10/poip.jpg",
            "detailsUrl": "https://cancerinstitutewia.in/",
            "phone": "+91-44-2220-9150",
            "contactEmail": "tncrp@cancerinstitutewia.org"
        },
        {
            "id": "apollo-chennai",
            "name": "Apollo Hospitals, Chennai (Greams Road) – Apollo Proton Cancer Centre",
            "city": "Chennai",
            "address": "21, Greams Lane, Off Greams Road, Chennai, Tamil Nadu – 600006",
            "established_year": 1983,
            "tier": "Tier 2",
            "accreditation": "JCI accredited, NABH accredited",
            "specializations": ["Breast Cancer", "GI Cancers", "Proton Therapy", "Robotic Surgery", "Bone Marrow Transplant", "Pediatric Oncology", "Common Cancers", "Rare Cancers", "DIPG", "Ewing's Sarcoma", "Chordoma", "HIPEC"],
            "success_rate": 95,
            "wait_time_days": 3,
            "beds_available": 20,
            "total_beds": 400,
            "treatments": ["Surgery", "Chemotherapy", "Radiation", "Proton Therapy", "Robotic Surgery", "Bone Marrow Transplant", "CAR-T Therapy", "HIPEC"],
            "cost_range": {"min": 500000, "max": 2500000},
            "accepts_insurance": True,
            "insurance_types": ["Mediclaim", "CGHS", "ESIC", "Ayushman Bharat", "Private Insurance"],
            "international_patients": True,
            "languages": ["English", "Tamil", "Hindi", "Telugu"],
            "rating": 4.9,
            "reviews_count": 3000,
            "image_url": "https://i.ytimg.com/vi/MR21VfcQEDI/hq720.jpg?sqp=-oaymwEhCK4FEIIDSFryq4qpAxMIARUAAAAAGAElAADIQj0AgKJD&rs=AOn4CLDLGXcdmQx0O-Mv8uKn0aglv6TM9g",
            "imageUrl": "https://i.ytimg.com/vi/MR21VfcQEDI/hq720.jpg?sqp=-oaymwEhCK4FEIIDSFryq4qpAxMIARUAAAAAGAElAADIQj0AgKJD&rs=AOn4CLDLGXcdmQx0O-Mv8uKn0aglv6TM9g",
            "detailsUrl": "https://www.apollohospitals.com/doctors?f%5B0%5D=cities%3A12",
            "appointmentUrl": "https://www.apollohospitals.com/doctors?f%5B0%5D=cities%3A12",
            "phone": "+91-8062972768",
            "contactEmail": "apcc@apollohospitals.com"
        },
        {
            "id": "gleneagles-chennai",
            "name": "Gleneagles Global Health City (Perumbakkam, Chennai)",
            "city": "Chennai",
            "address": "Cheran Nagar, Perumbakkam, Chennai, Tamil Nadu – 600100",
            "established_year": 2009,
            "tier": "Tier 2",
            "accreditation": "NABH and JCI accredited",
            "specializations": ["Liver Cancers", "Hepatobiliary Oncology", "Neuro-oncology", "Orthopedic Oncology", "Bone Marrow Transplant", "Transplant Oncology", "Common Cancers", "Rare Cancers", "Skull Base Tumors", "Spinal Tumors", "Sarcomas"],
            "success_rate": 91,
            "wait_time_days": 5,
            "beds_available": 11,
            "total_beds": 280,
            "treatments": ["Surgery", "Chemotherapy", "Radiation", "Liver Transplant", "Bone Marrow Transplant", "IG-IMRT", "Stereotactic Radiosurgery", "Clinical Trials"],
            "cost_range": {"min": 800000, "max": 3200000},
            "accepts_insurance": True,
            "insurance_types": ["Mediclaim", "Private Insurance"],
            "international_patients": True,
            "languages": ["English", "Tamil", "Hindi"],
            "rating": 4.7,
            "reviews_count": 1900,
            "image_url": "https://static.hospidio.com/uploads/hospital/51/gleneagles-hospital-chennai.jpeg.webp",
            "imageUrl": "https://static.hospidio.com/uploads/hospital/51/gleneagles-hospital-chennai.jpeg.webp",
            "detailsUrl": "https://www.gleneagleshospitals.co.in/doctors?types=book-an-appointment&hospital=3",
            "appointmentUrl": "https://www.gleneagleshospitals.co.in/doctors?types=book-an-appointment&hospital=3",
            "phone": "+91-92402-62425",
            "contactEmail": "info.chn@gleneagleshospitals.co.in"
        }
    ],
    "Pune": [
        {
            "id": "ruby-hall-pune",
            "name": "Ruby Hall Clinic (Ruby Hall Cancer Centre)",
            "city": "Pune",
            "address": "40, Sassoon Road, Pune, Maharashtra – 411001",
            "established_year": 1959,
            "tier": "Tier 2",
            "accreditation": "NABH accredited, NABL accredited",
            "specializations": ["Breast Cancer", "Lung Cancer", "Blood Cancers", "Lymphomas", "Gynecological Cancers", "Uro-oncology", "Bone Marrow Transplant", "Common Cancers", "Rare Cancers", "HIPEC"],
            "success_rate": 91,
            "wait_time_days": 5,
            "beds_available": 9,
            "total_beds": 150,
            "treatments": ["Surgery", "Chemotherapy", "Radiation", "Bone Marrow Transplant", "TrueBeam", "IMRT", "3D-CRT", "HIPEC"],
            "cost_range": {"min": 600000, "max": 2700000},
            "accepts_insurance": True,
            "insurance_types": ["Mediclaim", "Star Health", "CGHS"],
            "international_patients": True,
            "languages": ["English", "Hindi", "Marathi"],
            "rating": 4.6,
            "reviews_count": 1400,
            "image_url": "https://www.mgsarchitecture.in/images/Projects/293-GrantMedicalFoundation.jpg",
            "imageUrl": "https://www.mgsarchitecture.in/images/Projects/293-GrantMedicalFoundation.jpg",
            "detailsUrl": "https://rubyhallcancercentre.com/contact/index.html",
            "phone": "+91-20-66455573",
            "contactEmail": "cancercentre@rubyhall.com"
        },
        {
            "id": "deenanath-pune",
            "name": "Deenanath Mangeshkar Hospital & Research Center (DMHRC)",
            "city": "Pune",
            "address": "Erandwane, Near Mhatre Bridge, Pune, Maharashtra – 411004",
            "established_year": 2001,
            "tier": "Tier 2",
            "accreditation": "NABH and NABL accredited",
            "specializations": ["Surgical Oncology", "Medical Oncology", "Radiation Oncology", "Thoracic Oncology", "Head & Neck Oncology", "GI Oncology", "Common Cancers", "Rare Cancers", "Pediatric Cancers", "Brain Tumors", "Robotic Surgery"],
            "success_rate": 90,
            "wait_time_days": 6,
            "beds_available": 7,
            "total_beds": 220,
            "treatments": ["Surgery", "Chemotherapy", "Radiation", "Robotic Surgery", "Elekta Linear Accelerator", "Brachytherapy", "Liver Transplant"],
            "cost_range": {"min": 700000, "max": 2900000},
            "accepts_insurance": True,
            "insurance_types": ["Mediclaim", "Private Insurance"],
            "international_patients": True,
            "languages": ["English", "Hindi", "Marathi"],
            "rating": 4.6,
            "reviews_count": 1500,
            "image_url": "https://content.jdmagicbox.com/comp/pune/t2/020pxx20.xx20.000924773752.c2t2/catalogue/deenanath-mangeshkar-hospital-and-research-center-erandwane-pune-hospitals-vdhyu.jpg",
            "imageUrl": "https://content.jdmagicbox.com/comp/pune/t2/020pxx20.xx20.000924773752.c2t2/catalogue/deenanath-mangeshkar-hospital-and-research-center-erandwane-pune-hospitals-vdhyu.jpg",
            "detailsUrl": "https://www.dmhospital.org/contact-us",
            "phone": "+91-20-4015-1000",
            "contactEmail": "info@dmhospital.org"
        },
        {
            "id": "galaxy-pune",
            "name": "Galaxy CARE Hospital (Galaxy Institute of Oncology)",
            "city": "Pune",
            "address": "33, Karve Road, Erandwane, Pune, Maharashtra – 411004",
            "established_year": 2005,
            "tier": "Tier 3",
            "accreditation": "NABH accredited",
            "specializations": ["Gynecologic Oncology", "GI Oncology", "Uro-oncology", "Robotic Surgery", "Laparoscopic Surgery", "Common Cancers", "Select Rare Cancers"],
            "success_rate": 89,
            "wait_time_days": 7,
            "beds_available": 6,
            "total_beds": 120,
            "treatments": ["Surgery", "Chemotherapy", "Robotic Surgery", "Laparoscopic Surgery", "Minimally Invasive Procedures"],
            "cost_range": {"min": 800000, "max": 3000000},
            "accepts_insurance": True,
            "insurance_types": ["Mediclaim", "Private Insurance"],
            "international_patients": True,
            "languages": ["English", "Hindi", "Marathi"],
            "rating": 4.5,
            "reviews_count": 1200,
            "image_url": "https://www.galaxycare.org/custom/images/galaxy_care_facility1.jpg",
            "imageUrl": "https://www.galaxycare.org/custom/images/galaxy_care_facility1.jpg",
            "detailsUrl": "https://www.galaxycare.org/contact-us",
            "phone": "+91-20-67429800",
            "contactEmail": "info@galaxycare.org"
        }
    ],
    "Hyderabad": [
        {
            "id": "mnj-hyderabad",
            "name": "MNJ Institute of Oncology & Regional Cancer Centre, Hyderabad",
            "city": "Hyderabad",
            "address": "Red Hills, Lakdikapul, Hyderabad, Telangana – 500004",
            "established_year": 1955,
            "tier": "Tier 1",
            "accreditation": "State Cancer Institute",
            "specializations": ["Surgical Oncology", "Medical Oncology", "Radiation Oncology", "Pediatric Oncology", "Head-Neck Cancers", "Cervical Cancer", "Breast Cancer", "Lung Cancer", "Common Cancers", "Rare Cancers", "Palliative Care"],
            "success_rate": 92,
            "wait_time_days": 4,
            "beds_available": 12,
            "total_beds": 300,
            "treatments": ["Surgery", "Chemotherapy", "Radiation", "Cobalt-60", "Linear Accelerators", "Brachytherapy", "Palliative Care"],
            "cost_range": {"min": 400000, "max": 2000000},
            "accepts_insurance": True,
            "insurance_types": ["CGHS", "ESIC", "Ayushman Bharat"],
            "international_patients": True,
            "languages": ["English", "Hindi", "Telugu"],
            "rating": 4.7,
            "reviews_count": 2100,
            "image_url": "https://images.jdmagicbox.com/v2/comp/hyderabad/p8/040pxx40.xx40.170926150850.e4p8/catalogue/dr-jayanthi-mnj-institute-of-oncology-and-regional-cancer-centre-lakdi-ka-pool-khairatabad-hyderabad-oncologists-t6ikw8xxmo.jpg",
            "imageUrl": "https://images.jdmagicbox.com/v2/comp/hyderabad/p8/040pxx40.xx40.170926150850.e4p8/catalogue/dr-jayanthi-mnj-institute-of-oncology-and-regional-cancer-centre-lakdi-ka-pool-khairatabad-hyderabad-oncologists-t6ikw8xxmo.jpg",
            "detailsUrl": "https://www.mnjiorcc.in/html/contact-info.htm",
            "phone": "+91-40-23318422",
            "contactEmail": "info@mnjiorcc.org"
        },
        {
            "id": "basavatarakam-hyderabad",
            "name": "Basavatarakam Indo-American Cancer Hospital & Research Institute (BIACH&RI)",
            "city": "Hyderabad",
            "address": "Road No. 10, Nandi Nagar, Banjara Hills, Hyderabad, Telangana – 500034",
            "established_year": 2000,
            "tier": "Tier 1",
            "accreditation": "NABH accredited",
            "specializations": ["Medical Oncology", "Surgical Oncology", "Pediatric Oncology", "Radiation Oncology", "Bone Marrow Transplant", "Breast Cancer", "Lung Cancer", "Cervix Cancer", "Head-Neck Cancer", "Common Cancers", "Rare Cancers"],
            "success_rate": 93,
            "wait_time_days": 4,
            "beds_available": 15,
            "total_beds": 500,
            "treatments": ["Surgery", "Chemotherapy", "Radiation", "Bone Marrow Transplant", "IMRT/VMAT", "IGRT", "Hyperthermia", "Targeted Therapy"],
            "cost_range": {"min": 600000, "max": 2800000},
            "accepts_insurance": True,
            "insurance_types": ["Mediclaim", "CGHS", "Private Insurance"],
            "international_patients": True,
            "languages": ["English", "Hindi", "Telugu"],
            "rating": 4.8,
            "reviews_count": 2400,
            "image_url": "https://basavatarakam.org/wp-content/uploads/2022/02/best-cancer-hospital-in-hyderabad-basavatarakam-indo-american-cancer-hospital-scaled.jpg",
            "imageUrl": "https://basavatarakam.org/wp-content/uploads/2022/02/best-cancer-hospital-in-hyderabad-basavatarakam-indo-american-cancer-hospital-scaled.jpg",
            "detailsUrl": "https://basavatarakam.org/book-online-appointment/",
            "appointmentUrl": "https://basavatarakam.org/book-online-appointment/",
            "phone": "+91-1800-4253-6666",
            "contactEmail": "info@basavatarakam.org"
        },
        {
            "id": "aoi-hyderabad",
            "name": "American Oncology Institute (AOI), Hyderabad",
            "city": "Hyderabad",
            "address": "Serilingampally (Old Mumbai Hwy), Lingampally, Hyderabad, Telangana – 500019",
            "established_year": 2013,
            "tier": "Tier 2",
            "accreditation": "NABH accredited",
            "specializations": ["Breast Cancer", "Thoracic Oncology", "GI Oncology", "Uro-oncology", "Medical Oncology", "Radiation Oncology", "Surgical Oncology", "Common Cancers", "Rare Cancers", "Sarcomas", "Neuroendocrine Tumors"],
            "success_rate": 91,
            "wait_time_days": 5,
            "beds_available": 10,
            "total_beds": 200,
            "treatments": ["Surgery", "Chemotherapy", "Radiation", "IMRT/VMAT", "SBRT", "3D-CRT", "Targeted Therapy", "Immunotherapy", "Minimally Invasive Surgery"],
            "cost_range": {"min": 800000, "max": 3200000},
            "accepts_insurance": True,
            "insurance_types": ["Mediclaim", "Private Insurance"],
            "international_patients": True,
            "languages": ["English", "Hindi", "Telugu"],
            "rating": 4.7,
            "reviews_count": 1800,
            "image_url": "https://www.americanoncology.com/static/landingpage/oncologyhyderabad/images/aoi-hydrabadhp.JPG",
            "imageUrl": "https://www.americanoncology.com/static/landingpage/oncologyhyderabad/images/aoi-hydrabadhp.JPG",
            "detailsUrl": "https://www.americanoncology.com/bookanappointment",
            "appointmentUrl": "https://www.americanoncology.com/bookanappointment",
            "phone": "+91-1800-208-2000",
            "contactEmail": "contactus@americanoncology.com"
        },
        {
            "id": "yashoda-hyderabad",
            "name": "Yashoda Cancer Institute (Yashoda Hospitals, Hyderabad)",
            "city": "Hyderabad",
            "address": "Somajiguda and Malakpet, Hyderabad, Telangana",
            "established_year": 1990,
            "tier": "Tier 2",
            "accreditation": "NABH accredited, NABL accredited",
            "specializations": ["Medical Oncology", "Surgical Oncology", "Hematology-oncology", "Radiation Oncology", "Breast Cancer", "Cervical Cancer", "Lung Cancer", "Oral Cancer", "Blood Cancers", "Bone Marrow Transplant", "Common Cancers", "Rare Cancers"],
            "success_rate": 90,
            "wait_time_days": 6,
            "beds_available": 8,
            "total_beds": 250,
            "treatments": ["Surgery", "Chemotherapy", "Radiation", "Halcyon Linear Accelerator", "TrueBeam STx", "Bone Marrow Transplantation", "Robotic Surgery", "Laparoscopic Surgery"],
            "cost_range": {"min": 700000, "max": 3000000},
            "accepts_insurance": True,
            "insurance_types": ["Mediclaim", "Private Insurance"],
            "international_patients": True,
            "languages": ["English", "Hindi", "Telugu"],
            "rating": 4.6,
            "reviews_count": 1700,
            "image_url": "https://www.yashodahospitals.com/wp-content/uploads/2024/07/yashoda_malakpet-1.jpg",
            "imageUrl": "https://www.yashodahospitals.com/wp-content/uploads/2024/07/yashoda_malakpet-1.jpg",
            "detailsUrl": "https://www.yashodahospitals.com/contact-us/",
            "phone": "+91-8065906200",
            "contactEmail": "query@yashodamail.com"
        }
    ],
    "Nashik": [
        {
            "id": "hcg-manavata-nashik",
            "name": "HCG Manavata Cancer Centre, Nashik",
            "city": "Nashik",
            "address": "HCG Manavata Cancer Centre, Mumbai Naka, Nashik, Maharashtra – 422001",
            "established_year": 2007,
            "tier": "Tier 2",
            "accreditation": "NABH accredited",
            "specializations": ["Surgical Oncology", "Medical Oncology", "Radiation Oncology", "Breast Cancer", "Head-Neck Cancer", "GI Oncology", "Common Cancers", "Select Rare Cancers", "Pediatric Cancers"],
            "success_rate": 89,
            "wait_time_days": 7,
            "beds_available": 6,
            "total_beds": 100,
            "treatments": ["Surgery", "Chemotherapy", "Radiation", "3D-CRT", "IMRT", "Minimally Invasive Surgery", "Organ Preservation Protocols"],
            "cost_range": {"min": 500000, "max": 2200000},
            "accepts_insurance": True,
            "insurance_types": ["Mediclaim", "CGHS", "Private Insurance"],
            "international_patients": True,
            "languages": ["English", "Hindi", "Marathi"],
            "rating": 4.5,
            "reviews_count": 1100,
            "image_url": "https://www.hcgoncology.com/uploads/images/nasik-manavata-cancer-centre-banner.webp",
            "imageUrl": "https://www.hcgoncology.com/uploads/images/nasik-manavata-cancer-centre-banner.webp",
            "detailsUrl": "https://www.hcgmanavatacancer.org/book-an-appointment/",
            "appointmentUrl": "https://www.hcgmanavatacancer.org/book-an-appointment/",
            "phone": "+91-253-6661111",
            "contactEmail": "info@manavatacancercentre.com"
        },
        {
            "id": "ashoka-nashik",
            "name": "Ashoka Medicover Hospitals",
            "city": "Nashik",
            "address": "Wockhardt Circle, Mumbai-Agra Road, Nashik, Maharashtra – 422003",
            "established_year": 2008,
            "tier": "Tier 3",
            "accreditation": "NABH accredited",
            "specializations": ["Medical Oncology", "Surgical Oncology", "Breast Cancer", "Head-Neck Cancer", "GI Cancers", "Gynecologic Cancers", "Common Cancers", "Early-stage Cancers"],
            "success_rate": 87,
            "wait_time_days": 8,
            "beds_available": 5,
            "total_beds": 150,
            "treatments": ["Surgery", "Chemotherapy", "Targeted Therapy", "Basic Palliative Care"],
            "cost_range": {"min": 600000, "max": 2500000},
            "accepts_insurance": True,
            "insurance_types": ["Mediclaim", "Private Insurance"],
            "international_patients": True,
            "languages": ["English", "Hindi", "Marathi"],
            "rating": 4.4,
            "reviews_count": 900,
            "image_url": "https://www.hosmac.com/wp-content/uploads/2019/10/ashoka11.jpg",
            "imageUrl": "https://www.hosmac.com/wp-content/uploads/2019/10/ashoka11.jpg",
            "detailsUrl": "https://www.medicoverhospitals.in/appointment",
            "appointmentUrl": "https://www.medicoverhospitals.in/appointment",
            "phone": "+91-40-68334455",
            "contactEmail": "info@medicoverhospitals.in"
        },
        {
            "id": "namco-nashik",
            "name": "Namco Cancer Hospital (Nashik)",
            "city": "Nashik",
            "address": "Hirabai Haridas Vidyanagari, Amrutdham, Panchavati, Nashik, Maharashtra – 422003",
            "established_year": 2018,
            "tier": "Tier 3",
            "accreditation": "Basic quality standards",
            "specializations": ["Early-stage Cancers", "Breast Cancer", "Oral Cancer", "Cervical Cancer", "Common Cancers", "Basic Oncology Services"],
            "success_rate": 85,
            "wait_time_days": 10,
            "beds_available": 4,
            "total_beds": 50,
            "treatments": ["Basic Surgery", "Chemotherapy", "Cancer Screening", "Follow-up Care"],
            "cost_range": {"min": 300000, "max": 1500000},
            "accepts_insurance": True,
            "insurance_types": ["CGHS", "Ayushman Bharat"],
            "international_patients": False,
            "languages": ["English", "Hindi", "Marathi"],
            "rating": 4.3,
            "reviews_count": 600,
            "image_url": "https://doctorlistingingestionpr.blob.core.windows.net/doctorprofilepic/1670849683407_HospitalProfileImage_cf74c24b-597b-4eb5-b1e6-b6f599b5d700.png",
            "imageUrl": "https://doctorlistingingestionpr.blob.core.windows.net/doctorprofilepic/1670849683407_HospitalProfileImage_cf74c24b-597b-4eb5-b1e6-b6f599b5d700.png",
            "detailsUrl": "https://namcotrust.com/#",
            "phone": "+91-253-2530139",
            "contactEmail": "info@namcohospital.com"
        }
    ],
    # USA Cities
    "New York City": [
        {
            "id": "msk-nyc",
            "name": "Memorial Sloan Kettering Cancer Center",
            "city": "New York City",
            "address": "1275 York Avenue, New York, NY 10065, USA",
            "established_year": 1884,
            "tier": "Tier 1",
            "accreditation": "NCI-designated Comprehensive Cancer Center",
            "specializations": ["All Cancer Types", "Rare Cancers", "Pediatric Oncology", "Research Trials", "Immunotherapy", "CAR-T Therapy"],
            "success_rate": 96,
            "wait_time_days": 2,
            "beds_available": 20,
            "total_beds": 500,
            "treatments": ["Surgery", "Chemotherapy", "Radiation", "Immunotherapy", "CAR-T Therapy", "Proton Therapy", "Clinical Trials"],
            "cost_range": {"min": 5000000, "max": 20000000},
            "accepts_insurance": True,
            "insurance_types": ["Medicare", "Medicaid", "Private Insurance"],
            "international_patients": True,
            "languages": ["English", "Spanish", "Chinese"],
            "rating": 4.9,
            "reviews_count": 5000,
            "image_url": "https://www.mskcc.org/sites/default/files/images/2024/01/dsc_7550_ret_1200x800_0.jpg",
            "imageUrl": "https://www.mskcc.org/sites/default/files/images/2024/01/dsc_7550_ret_1200x800_0.jpg",
            "detailsUrl": "https://www.mskcc.org/appointments/international",
            "appointmentUrl": "https://www.mskcc.org/appointments/international",
            "phone": "+1-332-900-5155",
            "contactEmail": "International@mskcc.org"
        },
        {
            "id": "nyp-nyc",
            "name": "NewYork-Presbyterian Hospital - Weill Cornell Medical Center",
            "city": "New York City",
            "address": "525 East 68th Street, New York, NY 10065, USA",
            "established_year": 1771,
            "tier": "Tier 1",
            "accreditation": "NCI-designated Comprehensive Cancer Center",
            "specializations": ["All Cancer Types", "Rare Cancers", "Research Trials", "Immunotherapy"],
            "success_rate": 95,
            "wait_time_days": 3,
            "beds_available": 18,
            "total_beds": 450,
            "treatments": ["Surgery", "Chemotherapy", "Radiation", "Immunotherapy", "Clinical Trials"],
            "cost_range": {"min": 4500000, "max": 19000000},
            "accepts_insurance": True,
            "insurance_types": ["Medicare", "Medicaid", "Private Insurance"],
            "international_patients": True,
            "languages": ["English", "Spanish", "Chinese"],
            "rating": 4.8,
            "reviews_count": 4800,
            "image_url": "https://starrfoundation.org/wp-content/uploads/2025/02/NewYork-Presbyterian-1.webp",
            "imageUrl": "https://starrfoundation.org/wp-content/uploads/2025/02/NewYork-Presbyterian-1.webp",
            "detailsUrl": "https://www.nyp.org/documents/global/patient-intake-form_english.pdf",
            "phone": "+1-212-746-9100",
            "contactEmail": "globalservices@nyp.org"
        },
        {
            "id": "mount-sinai-nyc",
            "name": "Mount Sinai Hospital - Tisch Cancer Institute",
            "city": "New York City",
            "address": "1 Gustave L. Levy Place, New York, NY 10029, USA",
            "established_year": 1852,
            "tier": "Tier 1",
            "accreditation": "NCI-designated Comprehensive Cancer Center",
            "specializations": ["All Cancer Types", "Rare Cancers", "Research Trials"],
            "success_rate": 94,
            "wait_time_days": 4,
            "beds_available": 15,
            "total_beds": 400,
            "treatments": ["Surgery", "Chemotherapy", "Radiation", "Immunotherapy", "Clinical Trials"],
            "cost_range": {"min": 4000000, "max": 18000000},
            "accepts_insurance": True,
            "insurance_types": ["Medicare", "Medicaid", "Private Insurance"],
            "international_patients": True,
            "languages": ["English", "Spanish"],
            "rating": 4.8,
            "reviews_count": 4500,
            "image_url": "https://www.mountsinai.org/files/MSHealth/Assets/Global/Newsroom/2025/Release-Resize-TischNCI.png",
            "imageUrl": "https://www.mountsinai.org/files/MSHealth/Assets/Global/Newsroom/2025/Release-Resize-TischNCI.png",
            "detailsUrl": "https://www.mountsinai.org/care/international/services/cancer",
            "phone": "+1-212-241-1100",
            "contactEmail": "MSHPatientRelations@mountsinai.org"
        }
    ],
    "Boston": [
        {
            "id": "dfci-boston",
            "name": "Dana-Farber Cancer Institute",
            "city": "Boston",
            "address": "450 Brookline Avenue, Boston, MA 02215, USA",
            "established_year": 1947,
            "tier": "Tier 1",
            "accreditation": "NCI-designated Comprehensive Cancer Center",
            "specializations": ["All Cancer Types", "Pediatric Oncology", "Research Trials", "Immunotherapy"],
            "success_rate": 95,
            "wait_time_days": 3,
            "beds_available": 15,
            "total_beds": 400,
            "treatments": ["Surgery", "Chemotherapy", "Radiation", "Immunotherapy", "CAR-T Therapy", "Clinical Trials"],
            "cost_range": {"min": 4000000, "max": 18000000},
            "accepts_insurance": True,
            "insurance_types": ["Medicare", "Medicaid", "Private Insurance"],
            "international_patients": True,
            "languages": ["English", "Spanish"],
            "rating": 4.9,
            "reviews_count": 4500,
            "image_url": "https://55933-bcmed.s3.amazonaws.com/bcp/images/dmImage/SourceImage/dana-farber-exterior12.jpg",
            "imageUrl": "https://55933-bcmed.s3.amazonaws.com/bcp/images/dmImage/SourceImage/dana-farber-exterior12.jpg",
            "detailsUrl": "https://www.dana-farber.org/request-appointment",
            "appointmentUrl": "https://www.dana-farber.org/request-appointment",
            "phone": "+1-877-442-3324",
            "contactEmail": "danafarberinternational@dfci.harvard.edu"
        }
    ],
    "Houston": [
        {
            "id": "md-anderson-houston",
            "name": "MD Anderson Cancer Center",
            "city": "Houston",
            "address": "1515 Holcombe Boulevard, Houston, TX 77030, USA",
            "established_year": 1941,
            "tier": "Tier 1",
            "accreditation": "NCI-designated Comprehensive Cancer Center",
            "specializations": ["All Cancer Types", "Rare Cancers", "Research Trials", "Immunotherapy"],
            "success_rate": 96,
            "wait_time_days": 2,
            "beds_available": 25,
            "total_beds": 600,
            "treatments": ["Surgery", "Chemotherapy", "Radiation", "Immunotherapy", "Proton Therapy", "Clinical Trials"],
            "cost_range": {"min": 5000000, "max": 20000000},
            "accepts_insurance": True,
            "insurance_types": ["Medicare", "Medicaid", "Private Insurance"],
            "international_patients": True,
            "languages": ["English", "Spanish"],
            "rating": 4.9,
            "reviews_count": 6000,
            "image_url": "https://www.mdanderson.org/images/publications/cancerfrontline/MDACC_sunrise_exterior_019.jpg",
            "imageUrl": "https://www.mdanderson.org/images/publications/cancerfrontline/MDACC_sunrise_exterior_019.jpg",
            "detailsUrl": "https://www.mdanderson.org/about-md-anderson/contact-us/askmdanderson/appointments.html",
            "appointmentUrl": "https://www.mdanderson.org/about-md-anderson/contact-us/askmdanderson/appointments.html",
            "phone": "+1-713-745-0450",
            "contactEmail": "International@MDAnderson.org"
        }
    ],
    "Rochester (MN)": [
        {
            "id": "mayo-rochester",
            "name": "Mayo Clinic Cancer Center",
            "city": "Rochester (MN)",
            "address": "200 First Street SW, Rochester, MN 55905, USA",
            "established_year": 1889,
            "tier": "Tier 1",
            "accreditation": "NCI-designated Comprehensive Cancer Center",
            "specializations": ["All Cancer Types", "Rare Cancers", "Research Trials"],
            "success_rate": 95,
            "wait_time_days": 3,
            "beds_available": 20,
            "total_beds": 500,
            "treatments": ["Surgery", "Chemotherapy", "Radiation", "Immunotherapy", "Proton Therapy", "Clinical Trials"],
            "cost_range": {"min": 4000000, "max": 18000000},
            "accepts_insurance": True,
            "insurance_types": ["Medicare", "Medicaid", "Private Insurance"],
            "international_patients": True,
            "languages": ["English"],
            "rating": 4.9,
            "reviews_count": 5500,
            "image_url": "https://assets.mayoclinic.org/content/dam/media/global/images/2024/06/25/photo-campus-sunset-mayo-clinic-phoenix-az-636x318.jpg",
            "imageUrl": "https://assets.mayoclinic.org/content/dam/media/global/images/2024/06/25/photo-campus-sunset-mayo-clinic-phoenix-az-636x318.jpg",
            "detailsUrl": "https://www.mayoclinic.org/appointments",
            "appointmentUrl": "https://www.mayoclinic.org/appointments",
            "phone": "+1-507-738-4021",
            "contactEmail": "intl.isit@mayo.edu"
        }
    ],
    "Los Angeles": [
        {
            "id": "cedars-sinai-la",
            "name": "Cedars-Sinai Medical Center - Samuel Oschin Comprehensive Cancer Institute",
            "city": "Los Angeles",
            "address": "8700 Beverly Boulevard, Los Angeles, CA 90048, USA",
            "established_year": 1902,
            "tier": "Tier 1",
            "accreditation": "NCI-designated Comprehensive Cancer Center",
            "specializations": ["All Cancer Types", "Rare Cancers", "Research Trials"],
            "success_rate": 94,
            "wait_time_days": 4,
            "beds_available": 18,
            "total_beds": 450,
            "treatments": ["Surgery", "Chemotherapy", "Radiation", "Immunotherapy", "Clinical Trials"],
            "cost_range": {"min": 4500000, "max": 19000000},
            "accepts_insurance": True,
            "insurance_types": ["Medicare", "Medicaid", "Private Insurance"],
            "international_patients": True,
            "languages": ["English", "Spanish", "Chinese"],
            "rating": 4.8,
            "reviews_count": 4800,
            "image_url": "https://www.cedars-sinai.org/content/dam/cedars-sinai/social-media/images/cedars-sinai-fb.jpg",
            "imageUrl": "https://www.cedars-sinai.org/content/dam/cedars-sinai/social-media/images/cedars-sinai-fb.jpg",
            "detailsUrl": "https://www.cedars-sinai.org/contact/make-appointment.html",
            "appointmentUrl": "https://www.cedars-sinai.org/contact/make-appointment.html",
            "phone": "+1-310-423-7890",
            "contactEmail": "csinternational@cshs.org"
        }
    ],
    "Philadelphia": [
        {
            "id": "fox-chase-philadelphia",
            "name": "Fox Chase Cancer Center",
            "city": "Philadelphia",
            "address": "333 Cottman Avenue, Philadelphia, PA 19111, USA",
            "established_year": 1974,
            "tier": "Tier 1",
            "accreditation": "NCI-designated Comprehensive Cancer Center",
            "specializations": ["All Cancer Types", "Rare Cancers", "Research Trials"],
            "success_rate": 94,
            "wait_time_days": 4,
            "beds_available": 15,
            "total_beds": 400,
            "treatments": ["Surgery", "Chemotherapy", "Radiation", "Immunotherapy", "Clinical Trials"],
            "cost_range": {"min": 4000000, "max": 18000000},
            "accepts_insurance": True,
            "insurance_types": ["Medicare", "Medicaid", "Private Insurance"],
            "international_patients": True,
            "languages": ["English"],
            "rating": 4.8,
            "reviews_count": 4200,
            "image_url": "https://www.foxchase.org/sites/default/files/styles/slider_desktop/public/images/slide/slide_GENWestDay012560x1200_1.jpg?itok=8Sk3uINT",
            "imageUrl": "https://www.foxchase.org/sites/default/files/styles/slider_desktop/public/images/slide/slide_GENWestDay012560x1200_1.jpg?itok=8Sk3uINT",
            "detailsUrl": "https://www.foxchase.org/request-appointment",
            "appointmentUrl": "https://www.foxchase.org/request-appointment",
            "phone": "+1-267-559-5544",
            "contactEmail": "InternationalMedicine@fccc.edu"
        }
    ],
    "Baltimore": [
        {
            "id": "hopkins-baltimore",
            "name": "Johns Hopkins Sidney Kimmel Comprehensive Cancer Center",
            "city": "Baltimore",
            "address": "401 North Broadway, Baltimore, MD 21231, USA",
            "established_year": 1973,
            "tier": "Tier 1",
            "accreditation": "NCI-designated Comprehensive Cancer Center",
            "specializations": ["All Cancer Types", "Rare Cancers", "Research Trials"],
            "success_rate": 95,
            "wait_time_days": 3,
            "beds_available": 20,
            "total_beds": 500,
            "treatments": ["Surgery", "Chemotherapy", "Radiation", "Immunotherapy", "Clinical Trials"],
            "cost_range": {"min": 4500000, "max": 19000000},
            "accepts_insurance": True,
            "insurance_types": ["Medicare", "Medicaid", "Private Insurance"],
            "international_patients": True,
            "languages": ["English"],
            "rating": 4.9,
            "reviews_count": 5000,
            "image_url": "https://www.hopkinsmedicine.org/-/media/kimmel-cancer-center/images/kimmel-cancer-center/viragh.jpg",
            "imageUrl": "https://www.hopkinsmedicine.org/-/media/kimmel-cancer-center/images/kimmel-cancer-center/viragh.jpg",
            "detailsUrl": "https://mychart.hopkinsmedicine.org/MyChart/app/prospect-form?quickCrmId=WP-24de6ch432YNb-2BJC9uvFHG-2BA-3D-3D-24w-2BpJnH7o7-2FQT3NBLYgqzB9-2FxK4cHYIY4kUvjh-2B51Mgo-3D",
            "appointmentUrl": "https://mychart.hopkinsmedicine.org/MyChart/app/prospect-form?quickCrmId=WP-24de6ch432YNb-2BJC9uvFHG-2BA-3D-3D-24w-2BpJnH7o7-2FQT3NBLYgqzB9-2FxK4cHYIY4kUvjh-2B51Mgo-3D",
            "phone": "+1-410-502-7683",
            "contactEmail": "JHICare@jhmi.edu"
        }
    ],
    # Asia-Pacific
    "Singapore": [
        {
            "id": "ncc-singapore",
            "name": "National Cancer Centre Singapore",
            "city": "Singapore",
            "address": "30 Hospital Boulevard, Singapore 168583",
            "established_year": 2001,
            "tier": "Tier 1",
            "accreditation": "JCI accredited",
            "specializations": ["All Cancer Types", "Rare Cancers", "Research Trials"],
            "success_rate": 94,
            "wait_time_days": 3,
            "beds_available": 15,
            "total_beds": 400,
            "treatments": ["Surgery", "Chemotherapy", "Radiation", "Immunotherapy", "Proton Therapy", "Clinical Trials"],
            "cost_range": {"min": 3000000, "max": 15000000},
            "accepts_insurance": True,
            "insurance_types": ["Medisave", "Private Insurance"],
            "international_patients": True,
            "languages": ["English", "Mandarin", "Malay", "Tamil"],
            "rating": 4.8,
            "reviews_count": 3500,
            "image_url": "https://www.nccs.com.sg/adobe/dynamicmedia/deliver/dm-aid--020527a7-fba2-4ee3-b0cf-86ec370e7474/nccs-new-building-news.jpg?preferwebp=true",
            "imageUrl": "https://www.nccs.com.sg/adobe/dynamicmedia/deliver/dm-aid--020527a7-fba2-4ee3-b0cf-86ec370e7474/nccs-new-building-news.jpg?preferwebp=true",
            "detailsUrl": "https://eservices.healthhub.sg/public/appointments/make-new/form/request-form",
            "appointmentUrl": "https://eservices.healthhub.sg/public/appointments/make-new/form/request-form",
            "phone": "+65-6436-8088",
            "contactEmail": "callcentre@nccs.com.sg"
        }
    ],
    "Tokyo": [
        {
            "id": "ncch-tokyo",
            "name": "National Cancer Center Hospital",
            "city": "Tokyo",
            "address": "5-1-1 Tsukiji, Chuo-ku, Tokyo 104-0045, Japan",
            "established_year": 1962,
            "tier": "Tier 1",
            "accreditation": "JCI accredited",
            "specializations": ["All Cancer Types", "Rare Cancers", "Research Trials"],
            "success_rate": 94,
            "wait_time_days": 4,
            "beds_available": 18,
            "total_beds": 450,
            "treatments": ["Surgery", "Chemotherapy", "Radiation", "Immunotherapy", "Proton Therapy", "Clinical Trials"],
            "cost_range": {"min": 3500000, "max": 16000000},
            "accepts_insurance": True,
            "insurance_types": ["National Health Insurance", "Private Insurance"],
            "international_patients": True,
            "languages": ["Japanese", "English"],
            "rating": 4.8,
            "reviews_count": 4000,
            "image_url": "https://atlas.ncc.go.jp/atlasprj_cms/wp-content/uploads/ncc_hospital_image.jpg",
            "imageUrl": "https://atlas.ncc.go.jp/atlasprj_cms/wp-content/uploads/ncc_hospital_image.jpg",
            "detailsUrl": "https://www.nmct.ntt-east.co.jp/en/divisions/international_healthcare/",
            "appointmentUrl": "https://www.ncc.go.jp/en/about/appointments/index.html",
            "phone": "+81-3-6721-6239",
            "contactEmail": "nttihc-ml@east.ntt.co.jp"
        }
    ],
    "Osaka": [
        {
            "id": "osaka-cancer",
            "name": "Osaka International Cancer Institute",
            "city": "Osaka",
            "address": "3-1-69 Otemae, Chuo-ku, Osaka 540-0008, Japan",
            "established_year": 1938,
            "tier": "Tier 1",
            "accreditation": "JCI accredited",
            "specializations": ["All Cancer Types", "Rare Cancers", "Research Trials"],
            "success_rate": 93,
            "wait_time_days": 5,
            "beds_available": 15,
            "total_beds": 400,
            "treatments": ["Surgery", "Chemotherapy", "Radiation", "Immunotherapy", "Clinical Trials"],
            "cost_range": {"min": 3000000, "max": 15000000},
            "accepts_insurance": True,
            "insurance_types": ["National Health Insurance", "Private Insurance"],
            "international_patients": True,
            "languages": ["Japanese", "English"],
            "rating": 4.7,
            "reviews_count": 3500,
            "image_url": "https://www.japanhospitalsearch.org/contents/wp-content/uploads/2020/06/%E5%86%99%E7%9C%9F%E3%80%80%E5%A4%A7%E9%98%AA%E5%9B%BD%E9%9A%9B%E3%81%8C%E3%82%93%E3%82%BB%E3%83%B3%E3%82%BF%E3%83%BC%E3%80%80%E5%A4%96%E8%A6%B3.jpg",
            "imageUrl": "https://www.japanhospitalsearch.org/contents/wp-content/uploads/2020/06/%E5%86%99%E7%9C%9F%E3%80%80%E5%A4%A7%E9%98%AA%E5%9B%BD%E9%9A%9B%E3%81%8C%E3%82%93%E3%82%BB%E3%83%B3%E3%82%BF%E3%83%BC%E3%80%80%E5%A4%96%E8%A6%B3.jpg",
            "detailsUrl": "https://oici.jp.e.abv.hp.transer.com/hospital/#application",
            "appointmentUrl": "https://oici.jp.e.abv.hp.transer.com/hospital/#application",
            "phone": "+81-6-6945-1181",
            "contactEmail": None
        }
    ],
    # Middle East & Europe
    "Istanbul": [
        {
            "id": "memorial-sisli-istanbul",
            "name": "Memorial Sisli Hospital",
            "city": "Istanbul",
            "address": "Piyalepasa Bulvari, Sisli, Istanbul, Turkey",
            "established_year": 2000,
            "tier": "Tier 2",
            "accreditation": "JCI accredited",
            "specializations": ["All Cancer Types", "Rare Cancers"],
            "success_rate": 92,
            "wait_time_days": 4,
            "beds_available": 12,
            "total_beds": 300,
            "treatments": ["Surgery", "Chemotherapy", "Radiation", "Immunotherapy"],
            "cost_range": {"min": 2000000, "max": 10000000},
            "accepts_insurance": True,
            "insurance_types": ["Private Insurance"],
            "international_patients": True,
            "languages": ["Turkish", "English"],
            "rating": 4.7,
            "reviews_count": 2800,
            "image_url": "https://experts-medical.com/wp-content/uploads/2019/02/memorial-hospital-in-istanbul-jpg.jpg",
            "imageUrl": "https://experts-medical.com/wp-content/uploads/2019/02/memorial-hospital-in-istanbul-jpg.jpg",
            "detailsUrl": "https://www.memorial.com.tr/en/get-appointment",
            "appointmentUrl": "https://www.memorial.com.tr/en/get-appointment",
            "phone": "+90-549-639-3366",
            "contactEmail": "internationalpatients@memorial.com.tr"
        }
    ],
    "Ankara": [
        {
            "id": "hacettepe-ankara",
            "name": "Hacettepe University Cancer Institute",
            "city": "Ankara",
            "address": "Hacettepe University, Sihhiye, Ankara, Turkey",
            "established_year": 1967,
            "tier": "Tier 1",
            "accreditation": "JCI accredited",
            "specializations": ["All Cancer Types", "Rare Cancers", "Research Trials"],
            "success_rate": 93,
            "wait_time_days": 5,
            "beds_available": 15,
            "total_beds": 400,
            "treatments": ["Surgery", "Chemotherapy", "Radiation", "Immunotherapy", "Clinical Trials"],
            "cost_range": {"min": 1800000, "max": 9000000},
            "accepts_insurance": True,
            "insurance_types": ["National Insurance", "Private Insurance"],
            "international_patients": True,
            "languages": ["Turkish", "English"],
            "rating": 4.8,
            "reviews_count": 3200,
            "image_url": "https://www.university.com.tr/wp-content/uploads/2022/03/85_Hacettepe-University_Campus.jpg",
            "imageUrl": "https://www.university.com.tr/wp-content/uploads/2022/03/85_Hacettepe-University_Campus.jpg",
            "detailsUrl": "https://international.hacettepe.edu.tr/contact-information_407.html",
            "phone": "+90-312-305-2604",
            "contactEmail": "ipo@hacettepe.edu.tr"
        }
    ],
    "Toronto": [
        {
            "id": "princess-margaret-toronto",
            "name": "Princess Margaret Cancer Centre",
            "city": "Toronto",
            "address": "610 University Avenue, Toronto, ON M5G 2M9, Canada",
            "established_year": 1952,
            "tier": "Tier 1",
            "accreditation": "Accredited by Accreditation Canada",
            "specializations": ["All Cancer Types", "Rare Cancers", "Research Trials"],
            "success_rate": 95,
            "wait_time_days": 3,
            "beds_available": 20,
            "total_beds": 500,
            "treatments": ["Surgery", "Chemotherapy", "Radiation", "Immunotherapy", "Clinical Trials"],
            "cost_range": {"min": 2500000, "max": 12000000},
            "accepts_insurance": True,
            "insurance_types": ["OHIP", "Private Insurance"],
            "international_patients": True,
            "languages": ["English", "French"],
            "rating": 4.9,
            "reviews_count": 4500,
            "image_url": "https://cdn.prod.website-files.com/67dad124930e6770d64e9036/686fdeb92ace1a3d0517fee0_1423_header_image.jpg",
            "imageUrl": "https://cdn.prod.website-files.com/67dad124930e6770d64e9036/686fdeb92ace1a3d0517fee0_1423_header_image.jpg",
            "detailsUrl": "https://www.uhn.ca/IHP/International_Patients",
            "appointmentUrl": "https://www.uhn.ca/IHP/International_Patients",
            "phone": "+1-416-603-5015",
            "contactEmail": "IPP@uhn.ca"
        }
    ],
    "Vancouver": [
        {
            "id": "bccancer-vancouver",
            "name": "BC Cancer - Vancouver Centre",
            "city": "Vancouver",
            "address": "600 West 10th Avenue, Vancouver, BC V5Z 4E6, Canada",
            "established_year": 1938,
            "tier": "Tier 1",
            "accreditation": "Accredited by Accreditation Canada",
            "specializations": ["All Cancer Types", "Rare Cancers", "Research Trials"],
            "success_rate": 94,
            "wait_time_days": 4,
            "beds_available": 18,
            "total_beds": 450,
            "treatments": ["Surgery", "Chemotherapy", "Radiation", "Immunotherapy", "Clinical Trials"],
            "cost_range": {"min": 2200000, "max": 11000000},
            "accepts_insurance": True,
            "insurance_types": ["MSP", "Private Insurance"],
            "international_patients": True,
            "languages": ["English", "French", "Chinese"],
            "rating": 4.8,
            "reviews_count": 4000,
            "image_url": "https://henriquezpartners.com/wp-content/uploads/2018/08/henriquez-partners-bc-cancer-research-centre-2.jpg",
            "imageUrl": "https://henriquezpartners.com/wp-content/uploads/2018/08/henriquez-partners-bc-cancer-research-centre-2.jpg",
            "detailsUrl": "https://www.bccancer.bc.ca/our-services/patient-guide/out-of-province-out-of-country-patients#Out-of-country--patients",
            "phone": "+1-604-877-6000",
            "contactEmail": None
        }
    ],
    "Berlin": [
        {
            "id": "charite-berlin",
            "name": "Charité - Universitätsmedizin Berlin",
            "city": "Berlin",
            "address": "Charitéplatz 1, 10117 Berlin, Germany",
            "established_year": 1710,
            "tier": "Tier 1",
            "accreditation": "Certified by German Cancer Society (DKG)",
            "specializations": ["All Cancer Types", "Rare Cancers", "Research Trials"],
            "success_rate": 94,
            "wait_time_days": 4,
            "beds_available": 20,
            "total_beds": 500,
            "treatments": ["Surgery", "Chemotherapy", "Radiation", "Immunotherapy", "Clinical Trials"],
            "cost_range": {"min": 2000000, "max": 10000000},
            "accepts_insurance": True,
            "insurance_types": ["Public Insurance", "Private Insurance"],
            "international_patients": True,
            "languages": ["German", "English"],
            "rating": 4.8,
            "reviews_count": 4200,
            "image_url": "https://neurochirurgie.charite.de/fileadmin/_processed_/2/4/csm_Klinik-fuer-Neurochirurgie-Berlin_940x420_fd34177c4e.jpg",
            "imageUrl": "https://neurochirurgie.charite.de/fileadmin/_processed_/2/4/csm_Klinik-fuer-Neurochirurgie-Berlin_940x420_fd34177c4e.jpg",
            "detailsUrl": "https://www.charite.de/en/international/for_international_patients",
            "phone": "+49-30-450-578-244",
            "contactEmail": "international-patients@charite.de"
        }
    ],
    "Heidelberg": [
        {
            "id": "nct-heidelberg",
            "name": "National Center for Tumor Diseases (NCT) Heidelberg",
            "city": "Heidelberg",
            "address": "Im Neuenheimer Feld 460, 69120 Heidelberg, Germany",
            "established_year": 2004,
            "tier": "Tier 1",
            "accreditation": "Certified by German Cancer Society (DKG)",
            "specializations": ["All Cancer Types", "Rare Cancers", "Research Trials"],
            "success_rate": 95,
            "wait_time_days": 3,
            "beds_available": 18,
            "total_beds": 450,
            "treatments": ["Surgery", "Chemotherapy", "Radiation", "Immunotherapy", "Clinical Trials"],
            "cost_range": {"min": 2200000, "max": 11000000},
            "accepts_insurance": True,
            "insurance_types": ["Public Insurance", "Private Insurance"],
            "international_patients": True,
            "languages": ["German", "English"],
            "rating": 4.9,
            "reviews_count": 4500,
            "image_url": "https://modulo.net/files/chunks/5a5e416da0d55627f0000012/5a5e417ea0d55627d1000018.jpg",
            "imageUrl": "https://modulo.net/files/chunks/5a5e416da0d55627f0000012/5a5e417ea0d55627d1000018.jpg",
            "detailsUrl": "https://www.heidelberg-university-hospital.com/treatment-inquiry-appointment/cookies-notice-telemedicine-portal",
            "appointmentUrl": "https://www.heidelberg-university-hospital.com/treatment-inquiry-appointment/cookies-notice-telemedicine-portal",
            "phone": "+49-6221-56-6243",
            "contactEmail": "international.office@med.uni-heidelberg.de"
        }
    ],
    "Abu Dhabi": [
        {
            "id": "tawam-abu-dhabi",
            "name": "Tawam Hospital - Al Ain",
            "city": "Abu Dhabi",
            "address": "Al Ain, Abu Dhabi, UAE",
            "established_year": 1979,
            "tier": "Tier 2",
            "accreditation": "JCI accredited",
            "specializations": ["All Cancer Types", "Rare Cancers"],
            "success_rate": 92,
            "wait_time_days": 4,
            "beds_available": 12,
            "total_beds": 300,
            "treatments": ["Surgery", "Chemotherapy", "Radiation", "Immunotherapy"],
            "cost_range": {"min": 2500000, "max": 12000000},
            "accepts_insurance": True,
            "insurance_types": ["Thiqa", "Private Insurance"],
            "international_patients": True,
            "languages": ["Arabic", "English"],
            "rating": 4.7,
            "reviews_count": 2800,
            "image_url": "https://www.allocationassist.com/wp-content/uploads/2025/06/tawam-hospital.webp",
            "imageUrl": "https://www.allocationassist.com/wp-content/uploads/2025/06/tawam-hospital.webp",
            "detailsUrl": "https://www.seha.ae/international-patients",
            "appointmentUrl": "https://www.seha.ae/international-patients",
            "phone": "+971-3-767-7444",
            "contactEmail": "contact@seha.ae"
        }
    ],
    "Dubai": [
        {
            "id": "mediclinic-dubai",
            "name": "Mediclinic City Hospital - Dubai",
            "city": "Dubai",
            "address": "Dubai Healthcare City, Dubai, UAE",
            "established_year": 2008,
            "tier": "Tier 2",
            "accreditation": "JCI accredited",
            "specializations": ["All Cancer Types", "Rare Cancers"],
            "success_rate": 91,
            "wait_time_days": 5,
            "beds_available": 10,
            "total_beds": 280,
            "treatments": ["Surgery", "Chemotherapy", "Radiation", "Immunotherapy"],
            "cost_range": {"min": 2800000, "max": 13000000},
            "accepts_insurance": True,
            "insurance_types": ["DHA", "Private Insurance"],
            "international_patients": True,
            "languages": ["Arabic", "English"],
            "rating": 4.6,
            "reviews_count": 2400,
            "image_url": "https://media.assettype.com/gulfnews%2Fimport%2F2020%2F06%2F02%2FMediclinic-City-Hospital_17274486612_medium.jpg?w=1200&ar=40%3A21&auto=format%2Ccompress&ogImage=true&mode=crop&enlarge=true&overlay=false&overlay_position=bottom&overlay_width=100",
            "imageUrl": "https://media.assettype.com/gulfnews%2Fimport%2F2020%2F06%2F02%2FMediclinic-City-Hospital_17274486612_medium.jpg?w=1200&ar=40%3A21&auto=format%2Ccompress&ogImage=true&mode=crop&enlarge=true&overlay=false&overlay_position=bottom&overlay_width=100",
            "detailsUrl": "https://www.mediclinic.ae/en/corporate/book-an-appointment.html",
            "appointmentUrl": "https://www.mediclinic.ae/en/corporate/book-an-appointment.html",
            "phone": "+971-2-408-3511",
            "contactEmail": "info@mediclinic.ae"
        }
    ],
    "Oslo": [
        {
            "id": "oslo-radium",
            "name": "Oslo University Hospital - Radium Hospital",
            "city": "Oslo",
            "address": "Ullernchausseen 70, 0379 Oslo, Norway",
            "established_year": 1932,
            "tier": "Tier 1",
            "accreditation": "Accredited by Norwegian authorities",
            "specializations": ["All Cancer Types", "Rare Cancers", "Research Trials"],
            "success_rate": 94,
            "wait_time_days": 4,
            "beds_available": 18,
            "total_beds": 450,
            "treatments": ["Surgery", "Chemotherapy", "Radiation", "Immunotherapy", "Clinical Trials"],
            "cost_range": {"min": 3000000, "max": 15000000},
            "accepts_insurance": True,
            "insurance_types": ["National Insurance", "Private Insurance"],
            "international_patients": True,
            "languages": ["Norwegian", "English"],
            "rating": 4.8,
            "reviews_count": 3800,
            "image_url": "https://upload.wikimedia.org/wikipedia/commons/5/54/Rikshospitalet_Oslo.jpg",
            "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/5/54/Rikshospitalet_Oslo.jpg",
            "detailsUrl": "https://www.oslo-universitetssykehus.no/en/about-oslo-university-hospital/contact-us/",
            "phone": "+47-22-93-40-00",
            "contactEmail": None
        }
    ],
    "London": [
        {
            "id": "royal-marsden-london",
            "name": "The Royal Marsden Hospital",
            "city": "London",
            "address": "203 Fulham Road, London SW3 6JJ, UK",
            "established_year": 1851,
            "tier": "Tier 1",
            "accreditation": "ISO 9001, NHS",
            "specializations": ["All Cancer Types", "Rare Cancers", "Research Trials"],
            "success_rate": 95,
            "wait_time_days": 3,
            "beds_available": 20,
            "total_beds": 500,
            "treatments": ["Surgery", "Chemotherapy", "Radiation", "Immunotherapy", "Clinical Trials"],
            "cost_range": {"min": 2500000, "max": 12000000},
            "accepts_insurance": True,
            "insurance_types": ["NHS", "Private Insurance"],
            "international_patients": True,
            "languages": ["English"],
            "rating": 4.9,
            "reviews_count": 5000,
            "image_url": "https://lipalondon.com/wp-content/uploads/2024/02/royal-marsden-hospital.jpg",
            "imageUrl": "https://lipalondon.com/wp-content/uploads/2024/02/royal-marsden-hospital.jpg",
            "detailsUrl": "https://www.royalmarsden.nhs.uk/private-care/referrals",
            "appointmentUrl": "https://www.royalmarsden.nhs.uk/private-care/referrals",
            "phone": "+44-20-7808-2063",
            "contactEmail": "int@rmh.nhs.uk"
        }
    ],
    "Manchester": [
        {
            "id": "christie-manchester",
            "name": "The Christie NHS Foundation Trust",
            "city": "Manchester",
            "address": "Wilmslow Road, Manchester M20 4BX, UK",
            "established_year": 1901,
            "tier": "Tier 1",
            "accreditation": "NHS, ISO 9001",
            "specializations": ["All Cancer Types", "Rare Cancers", "Research Trials"],
            "success_rate": 94,
            "wait_time_days": 4,
            "beds_available": 18,
            "total_beds": 450,
            "treatments": ["Surgery", "Chemotherapy", "Radiation", "Immunotherapy", "Clinical Trials"],
            "cost_range": {"min": 2200000, "max": 11000000},
            "accepts_insurance": True,
            "insurance_types": ["NHS", "Private Insurance"],
            "international_patients": True,
            "languages": ["English"],
            "rating": 4.8,
            "reviews_count": 4500,
            "image_url": "https://www.cruk.manchester.ac.uk/wp-content/uploads/2024/11/21-01-HERO-TheChristie-2560x1200-c-center-1920x1080.jpeg",
            "imageUrl": "https://www.cruk.manchester.ac.uk/wp-content/uploads/2024/11/21-01-HERO-TheChristie-2560x1200-c-center-1920x1080.jpeg",
            "detailsUrl": "https://mft.nhs.uk/mymft/virtual-video-appointments/",
            "appointmentUrl": "https://mft.nhs.uk/mymft/virtual-video-appointments/",
            "phone": "+44-161-446-8107",
            "contactEmail": "cancer.information@christie.nhs.uk"
        }
    ],
    "Paris": [
        {
            "id": "gustave-roussy-paris",
            "name": "Gustave Roussy Cancer Campus",
            "city": "Paris",
            "address": "114 Rue Edouard Vaillant, 94805 Villejuif, France",
            "established_year": 1926,
            "tier": "Tier 1",
            "accreditation": "Accredited by French authorities",
            "specializations": ["All Cancer Types", "Rare Cancers", "Research Trials"],
            "success_rate": 95,
            "wait_time_days": 3,
            "beds_available": 20,
            "total_beds": 500,
            "treatments": ["Surgery", "Chemotherapy", "Radiation", "Immunotherapy", "Clinical Trials"],
            "cost_range": {"min": 2000000, "max": 10000000},
            "accepts_insurance": True,
            "insurance_types": ["Social Security", "Private Insurance"],
            "international_patients": True,
            "languages": ["French", "English"],
            "rating": 4.9,
            "reviews_count": 4800,
            "image_url": "https://www.gustaveroussy.fr/sites/default/files/gustaveroussy-fronton_16.jpg",
            "imageUrl": "https://www.gustaveroussy.fr/sites/default/files/gustaveroussy-fronton_16.jpg",
            "detailsUrl": "https://www.gustaveroussy.fr/en/international-appointment",
            "appointmentUrl": "https://rdv.gustaveroussy.fr/en",
            "phone": "+33-1-42-11-42-11",
            "contactEmail": "internationalpatients@gustaveroussy.fr"
        }
    ],
    "Lyon": [
        {
            "id": "leon-berard-lyon",
            "name": "Centre Léon Bérard",
            "city": "Lyon",
            "address": "28 Rue Laënnec, 69373 Lyon, France",
            "established_year": 1958,
            "tier": "Tier 1",
            "accreditation": "Accredited by French authorities",
            "specializations": ["All Cancer Types", "Rare Cancers", "Research Trials"],
            "success_rate": 94,
            "wait_time_days": 4,
            "beds_available": 18,
            "total_beds": 450,
            "treatments": ["Surgery", "Chemotherapy", "Radiation", "Immunotherapy", "Clinical Trials"],
            "cost_range": {"min": 1800000, "max": 9000000},
            "accepts_insurance": True,
            "insurance_types": ["Social Security", "Private Insurance"],
            "international_patients": True,
            "languages": ["French", "English"],
            "rating": 4.8,
            "reviews_count": 4200,
            "image_url": "https://www.centreleonberard.fr/sites/default/files/styles/paragraph_block_picture_and_text/public/2018-08/contact-centre-leon-berard.jpg?itok=R0uPWDxY",
            "imageUrl": "https://www.centreleonberard.fr/sites/default/files/styles/paragraph_block_picture_and_text/public/2018-08/contact-centre-leon-berard.jpg?itok=R0uPWDxY",
            "detailsUrl": "https://www.centreleonberard.fr/en/patient-relative/how-make-appointment",
            "appointmentUrl": "https://www.centreleonberard.fr/en/patient-relative/how-make-appointment",
            "phone": "+33-4-69-85-62-20",
            "contactEmail": "internationalpatient@lyon.unicancer.fr"
        }
    ],
    "Bangkok": [
        {
            "id": "bumrungrad-bangkok",
            "name": "Bumrungrad International Hospital",
            "city": "Bangkok",
            "address": "33 Sukhumvit 3, Khlong Toei Nuea, Watthana, Bangkok 10110, Thailand",
            "established_year": 1980,
            "tier": "Tier 2",
            "accreditation": "JCI accredited (first in Asia)",
            "specializations": ["All Cancer Types", "Rare Cancers"],
            "success_rate": 92,
            "wait_time_days": 4,
            "beds_available": 12,
            "total_beds": 300,
            "treatments": ["Surgery", "Chemotherapy", "Radiation", "Immunotherapy"],
            "cost_range": {"min": 1500000, "max": 8000000},
            "accepts_insurance": True,
            "insurance_types": ["National Insurance", "Private Insurance"],
            "international_patients": True,
            "languages": ["Thai", "English"],
            "rating": 4.7,
            "reviews_count": 3500,
            "image_url": "https://www.bumrungrad.com/getattachment/6e8a1bae-7bd6-4fc2-945a-5a61db4700ff/BH_Health-Screening-Programs.jpg",
            "imageUrl": "https://www.bumrungrad.com/getattachment/6e8a1bae-7bd6-4fc2-945a-5a61db4700ff/BH_Health-Screening-Programs.jpg",
            "detailsUrl": "https://www.bumrungrad.com/en/book-appointment",
            "appointmentUrl": "https://www.bumrungrad.com/en/book-appointment",
            "phone": "+66-2-066-8888",
            "contactEmail": "info@bumrungrad.com"
        }
    ]
}

# Doctor data
DOCTORS = [
    # Mumbai
    {"id": "dr-1", "name": "Dr. Rajesh Kumar", "specialty": "Surgical Oncology", "experience": 25, "city": "Mumbai", "hospital_id": "tmc-mumbai", "rating": 4.9, "consultations": 5000},
    {"id": "dr-2", "name": "Dr. Priya Sharma", "specialty": "Medical Oncology", "experience": 18, "city": "Mumbai", "hospital_id": "tmc-mumbai", "rating": 4.8, "consultations": 4200},
    {"id": "dr-3", "name": "Dr. Amit Patel", "specialty": "Radiation Oncology", "experience": 20, "city": "Mumbai", "hospital_id": "apollo-mumbai", "rating": 4.7, "consultations": 3800},
    
    # Bengaluru
    {"id": "dr-4", "name": "Dr. Sanjay Reddy", "specialty": "Surgical Oncology", "experience": 22, "city": "Bengaluru", "hospital_id": "hcg-bengaluru", "rating": 4.8, "consultations": 4500},
    {"id": "dr-5", "name": "Dr. Lakshmi Iyer", "specialty": "Medical Oncology", "experience": 16, "city": "Bengaluru", "hospital_id": "hcg-bengaluru", "rating": 4.7, "consultations": 3600},
    
    # Chennai
    {"id": "dr-6", "name": "Dr. Venkatesh Raman", "specialty": "Surgical Oncology", "experience": 28, "city": "Chennai", "hospital_id": "apollo-chennai", "rating": 4.9, "consultations": 6000},
    {"id": "dr-7", "name": "Dr. Meena Krishnan", "specialty": "Medical Oncology", "experience": 19, "city": "Chennai", "hospital_id": "apollo-chennai", "rating": 4.8, "consultations": 4800},
    
    # Pune
    {"id": "dr-8", "name": "Dr. Anil Deshmukh", "specialty": "Surgical Oncology", "experience": 21, "city": "Pune", "hospital_id": "ruby-hall-pune", "rating": 4.6, "consultations": 3400},
    {"id": "dr-9", "name": "Dr. Sneha Kulkarni", "specialty": "Radiation Oncology", "experience": 15, "city": "Pune", "hospital_id": "ruby-hall-pune", "rating": 4.5, "consultations": 2900},
    
    # Delhi
    {"id": "dr-10", "name": "Dr. Ashok Singh", "specialty": "Surgical Oncology", "experience": 30, "city": "Delhi", "hospital_id": "aiims-delhi", "rating": 4.9, "consultations": 7000},
    {"id": "dr-11", "name": "Dr. Nisha Gupta", "specialty": "Medical Oncology", "experience": 24, "city": "Delhi", "hospital_id": "rajiv-gandhi-delhi", "rating": 4.8, "consultations": 5200},
    {"id": "dr-12", "name": "Dr. Vikram Malhotra", "specialty": "Radiation Oncology", "experience": 19, "city": "New Delhi", "hospital_id": "aiims-delhi", "rating": 4.7, "consultations": 4100},
    
    # Additional doctors for expanded coverage
    # Mumbai doctors
    {"id": "dr-13", "name": "Dr. Suresh Menon", "specialty": "Medical Oncology", "experience": 22, "city": "Mumbai", "hospital_id": "tmc-mumbai", "rating": 4.8, "consultations": 4500},
    {"id": "dr-14", "name": "Dr. Anjali Desai", "specialty": "Pediatric Oncology", "experience": 20, "city": "Mumbai", "hospital_id": "tmc-mumbai", "rating": 4.9, "consultations": 4200},
    {"id": "dr-15", "name": "Dr. Ramesh Iyer", "specialty": "Surgical Oncology", "experience": 28, "city": "Mumbai", "hospital_id": "kdah-mumbai", "rating": 4.8, "consultations": 5000},
    {"id": "dr-16", "name": "Dr. Kavita Shah", "specialty": "Radiation Oncology", "experience": 18, "city": "Mumbai", "hospital_id": "jaslok-mumbai", "rating": 4.7, "consultations": 3800},
    {"id": "dr-17", "name": "Dr. Mahesh Patel", "specialty": "Medical Oncology", "experience": 25, "city": "Mumbai", "hospital_id": "fortis-mulund-mumbai", "rating": 4.8, "consultations": 4800},
    
    # New Delhi doctors
    {"id": "dr-18", "name": "Dr. Deepak Verma", "specialty": "Surgical Oncology", "experience": 26, "city": "New Delhi", "hospital_id": "rgcirc-delhi", "rating": 4.8, "consultations": 5200},
    {"id": "dr-19", "name": "Dr. Sunita Reddy", "specialty": "Medical Oncology", "experience": 21, "city": "New Delhi", "hospital_id": "apollo-delhi", "rating": 4.7, "consultations": 4600},
    {"id": "dr-20", "name": "Dr. Arvind Kumar", "specialty": "Radiation Oncology", "experience": 23, "city": "New Delhi", "hospital_id": "dharamshila-delhi", "rating": 4.8, "consultations": 4900},
    
    # Bengaluru doctors
    {"id": "dr-21", "name": "Dr. Ravi Shankar", "specialty": "Surgical Oncology", "experience": 27, "city": "Bengaluru", "hospital_id": "kidwai-bengaluru", "rating": 4.9, "consultations": 5500},
    {"id": "dr-22", "name": "Dr. Lakshmi Menon", "specialty": "Medical Oncology", "experience": 19, "city": "Bengaluru", "hospital_id": "hcg-bengaluru", "rating": 4.8, "consultations": 4400},
    {"id": "dr-23", "name": "Dr. Prakash Rao", "specialty": "Radiation Oncology", "experience": 24, "city": "Bengaluru", "hospital_id": "mazumdar-bengaluru", "rating": 4.9, "consultations": 5800},
    
    # Chennai doctors
    {"id": "dr-24", "name": "Dr. Senthil Kumar", "specialty": "Surgical Oncology", "experience": 29, "city": "Chennai", "hospital_id": "cancer-institute-chennai", "rating": 4.9, "consultations": 6200},
    {"id": "dr-25", "name": "Dr. Padma Iyer", "specialty": "Medical Oncology", "experience": 22, "city": "Chennai", "hospital_id": "apollo-chennai", "rating": 4.8, "consultations": 5000},
    {"id": "dr-26", "name": "Dr. Ramesh Krishnan", "specialty": "Radiation Oncology", "experience": 20, "city": "Chennai", "hospital_id": "gleneagles-chennai", "rating": 4.7, "consultations": 4700},
    
    # Hyderabad doctors
    {"id": "dr-27", "name": "Dr. Venkatesh Reddy", "specialty": "Surgical Oncology", "experience": 25, "city": "Hyderabad", "hospital_id": "basavatarakam-hyderabad", "rating": 4.8, "consultations": 5100},
    {"id": "dr-28", "name": "Dr. Anitha Rao", "specialty": "Medical Oncology", "experience": 18, "city": "Hyderabad", "hospital_id": "aoi-hyderabad", "rating": 4.7, "consultations": 4300},
    {"id": "dr-29", "name": "Dr. Srinivas Kumar", "specialty": "Radiation Oncology", "experience": 21, "city": "Hyderabad", "hospital_id": "yashoda-hyderabad", "rating": 4.8, "consultations": 4800},
    
    # Pune doctors
    {"id": "dr-30", "name": "Dr. Sameer Joshi", "specialty": "Surgical Oncology", "experience": 24, "city": "Pune", "hospital_id": "deenanath-pune", "rating": 4.7, "consultations": 4600},
    {"id": "dr-31", "name": "Dr. Neeta Kulkarni", "specialty": "Medical Oncology", "experience": 17, "city": "Pune", "hospital_id": "galaxy-pune", "rating": 4.6, "consultations": 4000},
    
    # International doctors - USA
    {"id": "dr-32", "name": "Dr. James Wilson", "specialty": "Medical Oncology", "experience": 30, "city": "New York City", "hospital_id": "msk-nyc", "rating": 4.9, "consultations": 8000},
    {"id": "dr-33", "name": "Dr. Sarah Johnson", "specialty": "Surgical Oncology", "experience": 28, "city": "New York City", "hospital_id": "msk-nyc", "rating": 4.9, "consultations": 7500},
    {"id": "dr-34", "name": "Dr. Michael Chen", "specialty": "Radiation Oncology", "experience": 25, "city": "New York City", "hospital_id": "nyp-nyc", "rating": 4.8, "consultations": 7000},
    {"id": "dr-35", "name": "Dr. Emily Davis", "specialty": "Pediatric Oncology", "experience": 22, "city": "Boston", "hospital_id": "dfci-boston", "rating": 4.9, "consultations": 6800},
    {"id": "dr-36", "name": "Dr. Robert Martinez", "specialty": "Medical Oncology", "experience": 32, "city": "Houston", "hospital_id": "md-anderson-houston", "rating": 4.9, "consultations": 8500},
    
    # Additional doctors to reach 300+ - adding in batches
    # Mumbai batch 1
    {"id": "dr-37", "name": "Dr. Rajesh Iyer", "specialty": "Surgical Oncology", "experience": 20, "city": "Mumbai", "hospital_id": "tmc-mumbai", "rating": 4.7, "consultations": 3500},
    {"id": "dr-38", "name": "Dr. Priya Menon", "specialty": "Medical Oncology", "experience": 19, "city": "Mumbai", "hospital_id": "kdah-mumbai", "rating": 4.8, "consultations": 4200},
    {"id": "dr-39", "name": "Dr. Amit Desai", "specialty": "Radiation Oncology", "experience": 21, "city": "Mumbai", "hospital_id": "jaslok-mumbai", "rating": 4.7, "consultations": 3900},
    {"id": "dr-40", "name": "Dr. Kavita Patel", "specialty": "Pediatric Oncology", "experience": 17, "city": "Mumbai", "hospital_id": "fortis-mulund-mumbai", "rating": 4.6, "consultations": 3200},
    
    # New Delhi batch 1
    {"id": "dr-41", "name": "Dr. Rajesh Kumar", "specialty": "Surgical Oncology", "experience": 24, "city": "New Delhi", "hospital_id": "aiims-delhi", "rating": 4.8, "consultations": 4800},
    {"id": "dr-42", "name": "Dr. Meera Sharma", "specialty": "Medical Oncology", "experience": 22, "city": "New Delhi", "hospital_id": "rgcirc-delhi", "rating": 4.7, "consultations": 4500},
    {"id": "dr-43", "name": "Dr. Suresh Reddy", "specialty": "Radiation Oncology", "experience": 20, "city": "New Delhi", "hospital_id": "apollo-delhi", "rating": 4.8, "consultations": 4700},
    
    # Note: To reach 300+ doctors, we would need to add 264 more entries.
    # For now, we have 43 doctors. The backend will calculate stats based on actual data.
    # Additional doctors can be added as needed.
]
