"""
Seed data for Rare Cancers API
Imports from the main data_seed.py file
"""
import sys
from pathlib import Path

# Add parent directory to path to import from data_seed
parent_dir = Path(__file__).parent.parent
sys.path.insert(0, str(parent_dir))

from data_seed import RARE_CANCERS, ALL_CANCERS


# Export for use in other modules
__all__ = ['RARE_CANCERS', 'ALL_CANCERS', 'RARE_CANCER_DETAILS', 'RARE_CANCER_SPECIALISTS']


# Enhanced rare cancer data with additional details
RARE_CANCER_DETAILS = {
    "Diffuse Intrinsic Pontine Glioma (DIPG)": {
        "description": "A highly aggressive brain tumor located in the pons region of the brainstem, primarily affecting children.",
        "symptoms": ["Difficulty walking", "Double vision", "Facial weakness", "Difficulty swallowing", "Headaches"],
        "treatment_options": ["Radiation therapy", "Clinical trials", "Palliative care", "Experimental therapies"],
        "prognosis": "Very poor, typically 9-12 months survival",
        "research_status": "Active research in immunotherapy and targeted therapies"
    },
    "Atypical Teratoid Rhabdoid Tumor (ATRT)": {
        "description": "A rare, aggressive tumor of the central nervous system, most commonly found in children under 3 years.",
        "symptoms": ["Headaches", "Nausea", "Vomiting", "Lethargy", "Cranial nerve deficits"],
        "treatment_options": ["Surgery", "High-dose chemotherapy", "Radiation therapy", "Stem cell transplant"],
        "prognosis": "Poor, but improved with aggressive multimodal therapy",
        "research_status": "Ongoing trials with targeted therapies"
    },
    "Embryonal Tumor with Multilayered Rosettes (ETMR)": {
        "description": "An ultra-rare, highly malignant pediatric brain tumor arising in young children, often involving the supratentorial region or brainstem.",
        "symptoms": ["Seizures", "Increased head size", "Vomiting", "Irritability", "Focal neurologic deficits"],
        "treatment_options": ["Maximal safe resection", "High-dose chemotherapy", "Radiation in selected cases", "Clinical trials"],
        "prognosis": "Generally poor, but outcomes are improving in specialized centers",
        "research_status": "Active research in genomics and novel targeted therapies"
    },
}


# Mapping of rare cancer -> list of global specialist oncologists
# Each specialist entry is intentionally compact but structured so it can be
# reused both by the RareCancers detail view and the Find Oncologists page.
RARE_CANCER_SPECIALISTS = {
    "Diffuse Intrinsic Pontine Glioma (DIPG)": [
        {
            "name": "Dr. Mark M. Souweidane",
            "region": "USA",
            "title": "Pediatric Neurosurgeon, Vice Chair of Neurological Surgery",
            "experience_years": 30,
            "city": "New York",
            "country": "USA",
            "institution": "Weill Cornell Medicine / NewYork-Presbyterian Hospital",
            "specialties": ["Pediatric brain tumors", "Brainstem tumors", "DIPG"],
        },
        {
            "name": "Dr. Enrica Tan",
            "region": "Singapore",
            "title": "Senior Consultant, Pediatric Oncologist",
            "experience_years": 15,
            "city": "Singapore",
            "country": "Singapore",
            "institution": "KK Women’s and Children’s Hospital (KKH)",
            "specialties": ["Pediatric neuro-oncology", "Brain tumors", "DIPG"],
        },
        {
            "name": "Dr. Jacques Grill",
            "region": "Europe",
            "title": "Head, Pediatric Brain Tumor Program",
            "experience_years": 20,
            "city": "Paris",
            "country": "France",
            "institution": "Gustave Roussy Cancer Campus",
            "specialties": ["Pediatric brain tumors", "DIPG", "Clinical trials"],
        },
        {
            "name": "Dr. Rakesh Jalali",
            "region": "India",
            "title": "Radiation Oncologist, Medical Director",
            "experience_years": 28,
            "city": "Chennai",
            "country": "India",
            "institution": "Apollo Proton Cancer Centre",
            "specialties": ["Pediatric brain tumors", "Proton therapy", "DIPG"],
        },
    ],
    "Atypical Teratoid Rhabdoid Tumor (ATRT)": [
        {
            "name": "Dr. Amar Gajjar",
            "region": "USA",
            "title": "Pediatric Neuro-Oncologist, Chair of Oncology",
            "experience_years": 35,
            "city": "Memphis",
            "country": "USA",
            "institution": "St. Jude Children’s Research Hospital",
            "specialties": ["Pediatric brain tumors", "ATRT", "Clinical research"],
        },
        {
            "name": "Dr. Soh Shui Yen",
            "region": "Singapore",
            "title": "Senior Consultant, Pediatric Hematology/Oncology",
            "experience_years": 15,
            "city": "Singapore",
            "country": "Singapore",
            "institution": "KK Women’s and Children’s Hospital (KKH)",
            "specialties": ["Pediatric CNS tumors", "ATRT", "Leukemias"],
        },
        {
            "name": "Prof. Darren Hargrave",
            "region": "Europe",
            "title": "Consultant Pediatric Neuro-Oncologist",
            "experience_years": 20,
            "city": "London",
            "country": "United Kingdom",
            "institution": "Great Ormond Street Hospital",
            "specialties": ["Pediatric brain tumors", "ATRT", "Early phase trials"],
        },
        {
            "name": "Dr. Girish Chinnaswamy",
            "region": "India",
            "title": "Professor & Head, Pediatric Oncology",
            "experience_years": 20,
            "city": "Mumbai",
            "country": "India",
            "institution": "Tata Memorial Centre",
            "specialties": ["Pediatric oncology", "Neuro-oncology", "ATRT"],
        },
    ],
    "Embryonal Tumor with Multilayered Rosettes (ETMR)": [
        {
            "name": "Dr. Maryam Fouladi",
            "region": "USA",
            "title": "Co-Director, Pediatric Neuro-Oncology Program",
            "experience_years": 20,
            "city": "Columbus",
            "country": "USA",
            "institution": "Nationwide Children’s Hospital",
            "specialties": ["Pediatric brain tumors", "ETMR", "Clinical trials"],
        },
        {
            "name": "Dr. Chan Mei Yoke",
            "region": "Singapore",
            "title": "Senior Consultant, Pediatric Oncology",
            "experience_years": 15,
            "city": "Singapore",
            "country": "Singapore",
            "institution": "KK Women’s and Children’s Hospital (KKH)",
            "specialties": ["Pediatric oncology", "Rare brain tumors", "ETMR"],
        },
        {
            "name": "Prof. Stefan Pfister",
            "region": "Europe",
            "title": "Director, Hopp Children’s Cancer Center",
            "experience_years": 15,
            "city": "Heidelberg",
            "country": "Germany",
            "institution": "Hopp Children’s Cancer Center / Heidelberg University",
            "specialties": ["Pediatric neuro-oncology", "Genomics", "ETMR"],
        },
        {
            "name": "Dr. Sameer Bakshi",
            "region": "India",
            "title": "Professor of Medical Oncology",
            "experience_years": 20,
            "city": "New Delhi",
            "country": "India",
            "institution": "AIIMS, New Delhi",
            "specialties": ["Pediatric and adolescent oncology", "Rare CNS tumors", "ETMR"],
        },
    ],
    "Midline NUT Carcinoma": [
        {
            "name": "Dr. Jia Luo",
            "region": "USA",
            "title": "Medical Oncologist, Thoracic Oncology",
            "experience_years": 15,
            "city": "Boston",
            "country": "USA",
            "institution": "Dana-Farber Cancer Institute",
            "specialties": ["Thoracic Oncology", "NUT Carcinoma", "Rare Carcinomas"],
        },
        {
            "name": "Dr. Toh Chee Keong",
            "region": "Singapore",
            "title": "Senior Consultant Medical Oncologist",
            "experience_years": 20,
            "city": "Singapore",
            "country": "Singapore",
            "institution": "NCCS/OncoCare",
            "specialties": ["Thoracic Oncology", "Head & Neck Cancers", "NUT Carcinoma"],
        },
        {
            "name": "Prof. Lisa Licitra",
            "region": "Europe",
            "title": "Head of Head & Neck Oncology",
            "experience_years": 30,
            "city": "Milan",
            "country": "Italy",
            "institution": "Istituto Nazionale Tumori",
            "specialties": ["Head & Neck Oncology", "Rare Head-Neck Cancers", "NUT Carcinoma"],
        },
        {
            "name": "Dr. Anil D'Cruz",
            "region": "India",
            "title": "Surgical Oncologist, Ex-Director",
            "experience_years": 33,
            "city": "Mumbai",
            "country": "India",
            "institution": "Tata Memorial Hospital",
            "specialties": ["Head-Neck Cancer", "Surgical Oncology", "NUT Carcinoma"],
        },
    ],
    "Small Cell Carcinoma of the Ovary, Hypercalcemic Type (SCCOHT)": [
        {
            "name": "Dr. Douglas A. Levine",
            "region": "USA",
            "title": "Gynecologic Oncologist",
            "experience_years": 25,
            "city": "New York",
            "country": "USA",
            "institution": "NYU Langone (formerly MSKCC)",
            "specialties": ["Gynecologic Oncology", "SCCOHT", "Ovarian Cancers"],
        },
        {
            "name": "Dr. Jeffrey Low",
            "region": "Singapore",
            "title": "Senior Consultant Gynecologic Oncologist",
            "experience_years": 20,
            "city": "Singapore",
            "country": "Singapore",
            "institution": "National University Cancer Institute Singapore (NUH)",
            "specialties": ["Gynecologic Oncology", "Rare Ovarian Cancers", "SCCOHT"],
        },
        {
            "name": "Prof. Susana Banerjee",
            "region": "Europe",
            "title": "Medical Oncologist",
            "experience_years": 24,
            "city": "London",
            "country": "United Kingdom",
            "institution": "Royal Marsden Hospital",
            "specialties": ["Gynecologic Cancers", "Rare Ovarian Tumors", "SCCOHT"],
        },
        {
            "name": "Dr. Amita Maheshwari",
            "region": "India",
            "title": "Professor & Head, Gyne-Oncology",
            "experience_years": 30,
            "city": "Mumbai",
            "country": "India",
            "institution": "Tata Memorial Hospital",
            "specialties": ["Gynecologic Oncology", "Rare Ovarian Cancers", "SCCOHT"],
        },
    ],
    "Anaplastic Thyroid Carcinoma (ATC)": [
        {
            "name": "Dr. Maria E. Cabanillas",
            "region": "USA",
            "title": "Oncologic Endocrinologist",
            "experience_years": 20,
            "city": "Houston",
            "country": "USA",
            "institution": "MD Anderson Cancer Center",
            "specialties": ["Endocrine Oncology", "Thyroid Cancer", "ATC"],
        },
        {
            "name": "Dr. Samantha Yang Peiling",
            "region": "Singapore",
            "title": "Endocrinologist",
            "experience_years": 15,
            "city": "Singapore",
            "country": "Singapore",
            "institution": "NCIS/NUH Singapore",
            "specialties": ["Thyroid Cancer", "Endocrinology", "ATC"],
        },
        {
            "name": "Prof. Martin Schlumberger",
            "region": "Europe",
            "title": "Oncologist",
            "experience_years": 40,
            "city": "Paris",
            "country": "France",
            "institution": "Gustave Roussy",
            "specialties": ["Thyroid Cancers", "Endocrine Oncology", "ATC"],
        },
        {
            "name": "Dr. Sanu P. Moideen",
            "region": "India",
            "title": "Head & Neck Oncosurgeon (ENT)",
            "experience_years": 25,
            "city": "Kerala",
            "country": "India",
            "institution": "Private Practice",
            "specialties": ["Head & Neck Surgery", "Thyroid Cancer", "ATC"],
        },
    ],
    "Desmoplastic Small Round Cell Tumor (DSRCT)": [
        {
            "name": "Dr. Andrea Hayes-Jordan",
            "region": "USA",
            "title": "Pediatric Surgical Oncologist",
            "experience_years": 25,
            "city": "Chapel Hill",
            "country": "USA",
            "institution": "UNC (formerly MD Anderson)",
            "specialties": ["Pediatric Surgical Oncology", "DSRCT", "HIPEC"],
        },
        {
            "name": "Dr. Richard Quek",
            "region": "Singapore",
            "title": "Senior Consultant Medical Oncologist",
            "experience_years": 16,
            "city": "Singapore",
            "country": "Singapore",
            "institution": "NCCS (formerly)",
            "specialties": ["Sarcoma Oncology", "DSRCT", "Multimodal Therapy"],
        },
        {
            "name": "Prof. Jeremy Whelan",
            "region": "Europe",
            "title": "Medical Oncologist",
            "experience_years": 24,
            "city": "London",
            "country": "United Kingdom",
            "institution": "UCLH",
            "specialties": ["Sarcoma Oncology", "Rare Abdominal Sarcomas", "DSRCT"],
        },
        {
            "name": "Dr. Sameer Rastogi",
            "region": "India",
            "title": "Sarcoma Medical Oncologist",
            "experience_years": 15,
            "city": "New Delhi",
            "country": "India",
            "institution": "AIIMS, New Delhi",
            "specialties": ["Sarcoma Oncology", "Rare Sarcomas", "DSRCT"],
        },
    ],
    "Epithelioid Hemangioendothelioma (EHE)": [
        {
            "name": "Dr. Vinod Ravi",
            "region": "USA",
            "title": "Sarcoma Medical Oncologist",
            "experience_years": 20,
            "city": "Houston",
            "country": "USA",
            "institution": "MD Anderson",
            "specialties": ["Sarcoma Oncology", "Vascular Sarcomas", "EHE"],
        },
        {
            "name": "Dr. Richard Quek",
            "region": "Singapore",
            "title": "Senior Consultant Medical Oncologist",
            "experience_years": 16,
            "city": "Singapore",
            "country": "Singapore",
            "institution": "Sarcoma Consortium",
            "specialties": ["Sarcoma Oncology", "EHE", "Rare Sarcomas"],
        },
        {
            "name": "Prof. Jean-Yves Blay",
            "region": "Europe",
            "title": "Oncologist, Director",
            "experience_years": 25,
            "city": "Lyon",
            "country": "France",
            "institution": "Centre Léon Bérard",
            "specialties": ["Rare Sarcomas", "EHE", "Angiosarcomas"],
        },
        {
            "name": "Dr. Sameer Rastogi",
            "region": "India",
            "title": "Sarcoma Medical Oncologist",
            "experience_years": 15,
            "city": "New Delhi",
            "country": "India",
            "institution": "AIIMS, New Delhi",
            "specialties": ["Sarcoma Oncology", "Rare Vascular Tumors", "EHE"],
        },
    ],
    "Histiocytic Sarcoma": [
        {
            "name": "Dr. Eli L. Diamond",
            "region": "USA",
            "title": "Neuro-oncologist",
            "experience_years": 10,
            "city": "New York",
            "country": "USA",
            "institution": "MSKCC",
            "specialties": ["Histiocytic Disorders", "Rare Histiocytic Neoplasms", "Histiocytic Sarcoma"],
        },
        {
            "name": "Dr. Kevin Tay",
            "region": "Singapore",
            "title": "Hematologist-Oncologist",
            "experience_years": 15,
            "city": "Singapore",
            "country": "Singapore",
            "institution": "OncoCare / NCCS",
            "specialties": ["Hematology-Oncology", "Lymphomas", "Histiocytic Sarcoma"],
        },
        {
            "name": "Dr. Julien Haroche",
            "region": "Europe",
            "title": "Internist",
            "experience_years": 20,
            "city": "Paris",
            "country": "France",
            "institution": "Pitié-Salpêtrière Hospital",
            "specialties": ["Histiocytoses", "Erdheim-Chester Disease", "Histiocytic Sarcoma"],
        },
        {
            "name": "Dr. Sameer Rastogi",
            "region": "India",
            "title": "Sarcoma Medical Oncologist",
            "experience_years": 15,
            "city": "New Delhi",
            "country": "India",
            "institution": "AIIMS, New Delhi",
            "specialties": ["Rare Cancer Specialist", "Histiocytic Sarcoma", "Multimodal Treatment"],
        },
    ],
    "Erdheim-Chester Disease (ECD)": [
        {
            "name": "Dr. Eli L. Diamond",
            "region": "USA",
            "title": "Neuro-oncologist",
            "experience_years": 10,
            "city": "New York",
            "country": "USA",
            "institution": "MSKCC",
            "specialties": ["Erdheim-Chester Disease", "Histiocytic Disorders", "Clinical Trials"],
        },
        {
            "name": "Dr. Chng Wee Joo",
            "region": "Singapore",
            "title": "Senior Hematologist",
            "experience_years": 40,
            "city": "Singapore",
            "country": "Singapore",
            "institution": "NUH",
            "specialties": ["Hematology", "Histiocytic Disorders", "ECD"],
        },
        {
            "name": "Dr. Julien Haroche",
            "region": "Europe",
            "title": "Internist",
            "experience_years": 20,
            "city": "Paris",
            "country": "France",
            "institution": "Pitié-Salpêtrière Hospital",
            "specialties": ["Erdheim-Chester Disease", "Histiocytic Neoplasms", "Targeted Therapies"],
        },
        {
            "name": "Dr. Sameer Rastogi",
            "region": "India",
            "title": "Sarcoma Medical Oncologist",
            "experience_years": 15,
            "city": "New Delhi",
            "country": "India",
            "institution": "AIIMS, New Delhi",
            "specialties": ["Rare Histiocytoses", "ECD", "Targeted Therapies"],
        },
    ],
    "Blastic Plasmacytoid Dendritic Cell Neoplasm (BPDCN)": [
        {
            "name": "Dr. Naveen Pemmaraju",
            "region": "USA",
            "title": "Hematologist-Oncologist",
            "experience_years": 10,
            "city": "Houston",
            "country": "USA",
            "institution": "MD Anderson",
            "specialties": ["Hematology-Oncology", "BPDCN", "Clinical Research"],
        },
        {
            "name": "Prof. Chng Wee Joo",
            "region": "Singapore",
            "title": "Senior Hematologist",
            "experience_years": 40,
            "city": "Singapore",
            "country": "Singapore",
            "institution": "NUH",
            "specialties": ["Hematology", "Rare Leukemias", "BPDCN"],
        },
        {
            "name": "Prof. Pier Luigi Zinzani",
            "region": "Europe",
            "title": "Hematologist",
            "experience_years": 30,
            "city": "Bologna",
            "country": "Italy",
            "institution": "University of Bologna",
            "specialties": ["Lymphoid Malignancies", "BPDCN", "Expert Panels"],
        },
        {
            "name": "Dr. Lalit Kumar",
            "region": "India",
            "title": "Medical Oncologist, Former Head of Medical Oncology",
            "experience_years": 30,
            "city": "New Delhi",
            "country": "India",
            "institution": "AIIMS, New Delhi",
            "specialties": ["Hemato-Oncology", "Blood Cancers", "BPDCN", "Bone Marrow Transplant"],
        },
    ],
    "T-cell Prolymphocytic Leukemia (T-PLL)": [
        {
            "name": "Dr. Susan O'Brien",
            "region": "USA",
            "title": "Hematologist",
            "experience_years": 30,
            "city": "Irvine",
            "country": "USA",
            "institution": "UC Irvine (formerly MD Anderson)",
            "specialties": ["Hematology", "CLL/T-PLL", "Alemtuzumab Trials"],
        },
        {
            "name": "Dr. Daryl Tan",
            "region": "Singapore",
            "title": "Hematologist",
            "experience_years": 20,
            "city": "Singapore",
            "country": "Singapore",
            "institution": "SGH",
            "specialties": ["Hematology", "Leukemias/Lymphomas", "T-PLL"],
        },
        {
            "name": "Dr. Hugues de Thé",
            "region": "Europe",
            "title": "Hematologist",
            "experience_years": 35,
            "city": "Paris",
            "country": "France",
            "institution": "Hôpital Saint-Louis",
            "specialties": ["Hematology", "T-cell Leukemias", "T-PLL"],
        },
        {
            "name": "Dr. Lalit Kumar",
            "region": "India",
            "title": "Medical Oncologist",
            "experience_years": 30,
            "city": "New Delhi",
            "country": "India",
            "institution": "AIIMS, New Delhi",
            "specialties": ["Hematologic Cancers", "Rare Leukemias", "T-PLL"],
        },
    ],
    "Hepatosplenic T-cell Lymphoma (HSTCL)": [
        {
            "name": "Dr. Steven Horwitz",
            "region": "USA",
            "title": "Medical Oncologist",
            "experience_years": 20,
            "city": "New York",
            "country": "USA",
            "institution": "MSKCC",
            "specialties": ["T-cell Lymphoma", "HSTCL", "Novel Immunotherapies"],
        },
        {
            "name": "Dr. Lim Soon Thye",
            "region": "Singapore",
            "title": "Medical Oncologist",
            "experience_years": 25,
            "city": "Singapore",
            "country": "Singapore",
            "institution": "NCCS",
            "specialties": ["Lymphoma Service", "T-cell Lymphomas", "HSTCL"],
        },
        {
            "name": "Prof. Marie José Kersten",
            "region": "Europe",
            "title": "Hematologist",
            "experience_years": 20,
            "city": "Amsterdam",
            "country": "Netherlands",
            "institution": "NKI/AVL",
            "specialties": ["T-cell Lymphomas", "HSTCL", "European Outcomes"],
        },
        {
            "name": "Dr. Lalit Kumar",
            "region": "India",
            "title": "Medical Oncologist, Former Head of Medical Oncology",
            "experience_years": 30,
            "city": "New Delhi",
            "country": "India",
            "institution": "AIIMS, New Delhi",
            "specialties": ["Hemato-Oncology", "Blood Cancers", "HSTCL", "T-cell Lymphomas"],
        },
    ],
    "Malignant Rhabdoid Tumor": [
        {
            "name": "Dr. Jack Su",
            "region": "USA",
            "title": "Pediatric Oncologist",
            "experience_years": 15,
            "city": "Houston",
            "country": "USA",
            "institution": "Texas Children's Hospital",
            "specialties": ["Pediatric Oncology", "MRT", "INI1-targeted Therapies"],
        },
        {
            "name": "Dr. Ann-Marie Teo",
            "region": "Singapore",
            "title": "Pediatric Oncologist",
            "experience_years": 15,
            "city": "Singapore",
            "country": "Singapore",
            "institution": "KK Women's and Children's Hospital (KKH)",
            "specialties": ["Pediatric Oncology", "MRT", "Multidisciplinary Care"],
        },
        {
            "name": "Dr. Dominique Valteau-Couanet",
            "region": "Europe",
            "title": "Pediatric Oncologist",
            "experience_years": 30,
            "city": "Villejuif",
            "country": "France",
            "institution": "Gustave Roussy",
            "specialties": ["Pediatric Solid Tumors", "MRT", "Intensive Multimodal Regimens"],
        },
        {
            "name": "Dr. Girish Chinnaswamy",
            "region": "India",
            "title": "Professor & Head, Pediatric Oncology",
            "experience_years": 20,
            "city": "Mumbai",
            "country": "India",
            "institution": "Tata Memorial Centre",
            "specialties": ["Pediatric Oncology", "MRT", "Intensive Multimodal Therapy"],
        },
    ],
    "Alveolar Soft Part Sarcoma (ASPS)": [
        {
            "name": "Dr. Breelyn Wilky",
            "region": "USA",
            "title": "Sarcoma Oncologist",
            "experience_years": 10,
            "city": "Denver",
            "country": "USA",
            "institution": "UCHealth",
            "specialties": ["Sarcoma Oncology", "ASPS", "TKI Trials"],
        },
        {
            "name": "Dr. Richard Quek",
            "region": "Singapore",
            "title": "Senior Consultant Medical Oncologist",
            "experience_years": 16,
            "city": "Singapore",
            "country": "Singapore",
            "institution": "Sarcoma Specialist",
            "specialties": ["Sarcoma Oncology", "ASPS", "Targeted Therapies"],
        },
        {
            "name": "Dr. Peter Hohenberger",
            "region": "Europe",
            "title": "Surgical Oncologist",
            "experience_years": 25,
            "city": "Mannheim",
            "country": "Germany",
            "institution": "University Hospital Mannheim",
            "specialties": ["Soft-tissue Sarcomas", "ASPS", "Surgical Resection"],
        },
        {
            "name": "Dr. Ashish Gulia",
            "region": "India",
            "title": "Orthopedic Oncologist",
            "experience_years": 15,
            "city": "Mumbai",
            "country": "India",
            "institution": "Tata Memorial",
            "specialties": ["Orthopedic Oncology", "ASPS", "Sarcoma Guidelines"],
        },
    ],
    "Clear Cell Sarcoma": [
        {
            "name": "Dr. Mark Dickson",
            "region": "USA",
            "title": "Medical Oncologist",
            "experience_years": 15,
            "city": "New York",
            "country": "USA",
            "institution": "MSKCC",
            "specialties": ["Rare Sarcomas", "Clear Cell Sarcoma", "Immunotherapy"],
        },
        {
            "name": "Dr. Wong Seng Weng",
            "region": "Singapore",
            "title": "Medical Oncologist",
            "experience_years": 20,
            "city": "Singapore",
            "country": "Singapore",
            "institution": "Parkway Cancer Centre",
            "specialties": ["Melanocytic Clear Cell Sarcoma", "Novel Agents", "Sarcoma"],
        },
        {
            "name": "Prof. Paolo Casali",
            "region": "Europe",
            "title": "Medical Oncologist",
            "experience_years": 30,
            "city": "Milan",
            "country": "Italy",
            "institution": "Istituto Nazionale Tumori (INT)",
            "specialties": ["Sarcoma Oncology", "Clear Cell Sarcoma", "Systemic Therapy"],
        },
        {
            "name": "Dr. Sameer Rastogi",
            "region": "India",
            "title": "Sarcoma Medical Oncologist",
            "experience_years": 15,
            "city": "New Delhi",
            "country": "India",
            "institution": "AIIMS, New Delhi",
            "specialties": ["Sarcoma Clinic", "Clear Cell Sarcoma", "Targeted Therapy"],
        },
    ],
    "Angiosarcoma": [
        {
            "name": "Dr. Sandra D'Angelo",
            "region": "USA",
            "title": "Medical Oncologist",
            "experience_years": 15,
            "city": "New York",
            "country": "USA",
            "institution": "MSKCC",
            "specialties": ["Angiosarcoma", "Immunotherapy Combinations", "Clinical Trials"],
        },
        {
            "name": "Dr. Toh Wei Peng",
            "region": "Singapore",
            "title": "Surgical Oncologist",
            "experience_years": 20,
            "city": "Singapore",
            "country": "Singapore",
            "institution": "National Cancer Centre",
            "specialties": ["Surgical Oncology", "Head/Neck Angiosarcoma", "Multimodal Therapy"],
        },
        {
            "name": "Prof. Henrik Falch",
            "region": "Europe",
            "title": "Surgical Oncologist",
            "experience_years": 20,
            "city": "Copenhagen",
            "country": "Denmark",
            "institution": "University Hospital Copenhagen",
            "specialties": ["Cutaneous Angiosarcoma", "Surgery", "Intralesional Therapy"],
        },
        {
            "name": "Dr. Navin Khattry",
            "region": "India",
            "title": "Medical Oncologist",
            "experience_years": 15,
            "city": "Mumbai",
            "country": "India",
            "institution": "ACTREC",
            "specialties": ["Rare Sarcomas", "Angiosarcoma", "Metronomic Regimens"],
        },
    ],
    "Chordoma": [
        {
            "name": "Dr. Ian F. Pollack",
            "region": "USA",
            "title": "Neurosurgeon",
            "experience_years": 30,
            "city": "Pittsburgh",
            "country": "USA",
            "institution": "University of Pittsburgh",
            "specialties": ["Skull-base Surgery", "Chordoma", "Proton Therapy"],
        },
        {
            "name": "Dr. Iqbal Muttaqin",
            "region": "Singapore",
            "title": "Neurosurgeon",
            "experience_years": 20,
            "city": "Singapore",
            "country": "Singapore",
            "institution": "NCCS Singapore",
            "specialties": ["Spine/Skull-base Tumors", "Chordoma", "Advanced Techniques"],
        },
        {
            "name": "Prof. Ralph Weber",
            "region": "Europe",
            "title": "Orthopedic Surgeon",
            "experience_years": 25,
            "city": "Berlin",
            "country": "Germany",
            "institution": "Charité Berlin",
            "specialties": ["Chordoma Resection", "Sacral/Pelvic Sites", "Proton Centers"],
        },
        {
            "name": "Dr. S. Karunakaran",
            "region": "India",
            "title": "Neurosurgeon",
            "experience_years": 20,
            "city": "Chennai",
            "country": "India",
            "institution": "Apollo Hospitals",
            "specialties": ["Skull-base Surgery", "Clival/Sacral Chordoma", "Proton Therapy"],
        },
    ],
    "Adrenocortical Carcinoma (ACC)": [
        {
            "name": "Dr. Gary D. Hammer",
            "region": "USA",
            "title": "Endocrine Oncologist",
            "experience_years": 25,
            "city": "Ann Arbor",
            "country": "USA",
            "institution": "University of Michigan",
            "specialties": ["Endocrine Oncology", "ACC", "Clinical Trials"],
        },
        {
            "name": "Dr. Khoo Kei Siong",
            "region": "Singapore",
            "title": "Medical Oncologist",
            "experience_years": 30,
            "city": "Singapore",
            "country": "Singapore",
            "institution": "Parkway Cancer Centre",
            "specialties": ["Medical Oncology", "ACC", "Mitotane Therapy"],
        },
        {
            "name": "Prof. Martin Fassnacht",
            "region": "Europe",
            "title": "Endocrinologist",
            "experience_years": 20,
            "city": "Würzburg",
            "country": "Germany",
            "institution": "University of Würzburg",
            "specialties": ["Endocrinology", "ACC Research", "European Guidelines"],
        },
        {
            "name": "Dr. Rajeev Agarwal",
            "region": "India",
            "title": "Surgical Oncologist",
            "experience_years": 30,
            "city": "New Delhi",
            "country": "India",
            "institution": "Private Practice",
            "specialties": ["Adrenal Tumor Surgery", "ACC", "Multidisciplinary Management"],
        },
    ],
    "Merkel Cell Carcinoma": [
        {
            "name": "Dr. Paul Nghiem",
            "region": "USA",
            "title": "Dermatologic Oncologist",
            "experience_years": 20,
            "city": "Seattle",
            "country": "USA",
            "institution": "UW/Fred Hutch",
            "specialties": ["Dermatologic Oncology", "Merkel Cell Carcinoma", "Immunotherapy"],
        },
        {
            "name": "Dr. Lee Soo Chin",
            "region": "Singapore",
            "title": "Medical Oncologist",
            "experience_years": 25,
            "city": "Singapore",
            "country": "Singapore",
            "institution": "NCIS",
            "specialties": ["Medical Oncology", "Merkel Cell Carcinoma", "Checkpoint Inhibitors"],
        },
        {
            "name": "Prof. Dirk Schadendorf",
            "region": "Europe",
            "title": "Dermatologic Oncologist",
            "experience_years": 30,
            "city": "Essen",
            "country": "Germany",
            "institution": "University Hospital Essen",
            "specialties": ["Dermatologic Oncology", "Merkel Cell Carcinoma", "Clinical Trials"],
        },
        {
            "name": "Dr. Nikhil Vasudev",
            "region": "India",
            "title": "Medical Oncologist",
            "experience_years": 15,
            "city": "Mumbai",
            "country": "India",
            "institution": "Tata Memorial",
            "specialties": ["Medical Oncology", "Merkel Cell Carcinoma", "Rare Skin Cancers"],
        },
    ],
    "Uveal Melanoma": [
        {
            "name": "Dr. Takami Sato",
            "region": "USA",
            "title": "Medical Oncologist",
            "experience_years": 30,
            "city": "Philadelphia",
            "country": "USA",
            "institution": "Jefferson Hospital",
            "specialties": ["Uveal Melanoma", "Hepatic Perfusion", "Clinical Trials"],
        },
        {
            "name": "Dr. Adrian Tan",
            "region": "Singapore",
            "title": "Senior Consultant Ophthalmologist",
            "experience_years": 20,
            "city": "Singapore",
            "country": "Singapore",
            "institution": "SNEC",
            "specialties": ["Ocular Oncology", "Uveal Melanoma", "Plaque Brachytherapy"],
        },
        {
            "name": "Prof. Sarah Coupland",
            "region": "Europe",
            "title": "Ocular Pathologist/Oncologist",
            "experience_years": 25,
            "city": "Liverpool",
            "country": "United Kingdom",
            "institution": "University of Liverpool",
            "specialties": ["Ocular Oncology", "Uveal Melanoma Research", "Ocular Tumors"],
        },
        {
            "name": "Dr. Santosh Honavar",
            "region": "India",
            "title": "Ocular Oncologist",
            "experience_years": 25,
            "city": "Hyderabad",
            "country": "India",
            "institution": "LV Prasad Eye Institute",
            "specialties": ["Ocular Oncology", "Uveal Melanoma", "Plaque Radiotherapy"],
        },
    ],
    "Fibrolamellar Hepatocellular Carcinoma (FL-HCC)": [
        {
            "name": "Dr. Milind Javle",
            "region": "USA",
            "title": "Medical Oncologist",
            "experience_years": 20,
            "city": "Houston",
            "country": "USA",
            "institution": "MD Anderson",
            "specialties": ["Hepatobiliary Oncology", "FL-HCC", "Targeted Therapy"],
        },
        {
            "name": "Dr. Pierce Chow",
            "region": "Singapore",
            "title": "Hepatobiliary Surgeon",
            "experience_years": 25,
            "city": "Singapore",
            "country": "Singapore",
            "institution": "NCCS/NHCS",
            "specialties": ["Hepatobiliary Surgery", "FL-HCC", "Liver Tumor Board"],
        },
        {
            "name": "Prof. Philip Johnson",
            "region": "Europe",
            "title": "Hepatologist",
            "experience_years": 30,
            "city": "London",
            "country": "United Kingdom",
            "institution": "University College London",
            "specialties": ["Hepatology", "FL-HCC Registry", "Management Guidelines"],
        },
        {
            "name": "Dr. Shripad Banavali",
            "region": "India",
            "title": "Medical Oncologist",
            "experience_years": 30,
            "city": "Mumbai",
            "country": "India",
            "institution": "Tata Memorial",
            "specialties": ["Medical Oncology", "Rare Liver Tumors", "FL-HCC"],
        },
    ],
    "Adenoid Cystic Carcinoma (ACC – Salivary)": [
        {
            "name": "Dr. Alan L. Ho",
            "region": "USA",
            "title": "Medical Oncologist",
            "experience_years": 15,
            "city": "New York",
            "country": "USA",
            "institution": "MSKCC",
            "specialties": ["Head & Neck Oncology", "Adenoid Cystic Carcinoma", "Targeted Agents"],
        },
        {
            "name": "Dr. Gopal Iyer",
            "region": "Singapore",
            "title": "Head & Neck Surgeon",
            "experience_years": 20,
            "city": "Singapore",
            "country": "Singapore",
            "institution": "SingHealth",
            "specialties": ["Head & Neck Surgery", "Salivary Gland Tumors", "Molecular Targets"],
        },
        {
            "name": "Prof. Laura V. Locati",
            "region": "Europe",
            "title": "Medical Oncologist",
            "experience_years": 20,
            "city": "Milan",
            "country": "Italy",
            "institution": "Istituto Nazionale Tumori",
            "specialties": ["Salivary Gland Cancers", "Adenoid Cystic Carcinoma", "European Guidelines"],
        },
        {
            "name": "Dr. Pankaj Chaturvedi",
            "region": "India",
            "title": "Head & Neck Surgical Oncologist",
            "experience_years": 25,
            "city": "Mumbai",
            "country": "India",
            "institution": "Tata Memorial",
            "specialties": ["Head & Neck Surgery", "Adenoid Cystic Carcinoma", "Postoperative Radiotherapy"],
        },
    ],
    "Esthesioneuroblastoma": [
        {
            "name": "Dr. Alexander G. Chiu",
            "region": "USA",
            "title": "Head & Neck Surgeon",
            "experience_years": 20,
            "city": "Phoenix",
            "country": "USA",
            "institution": "Mayo Clinic",
            "specialties": ["Head & Neck Surgery", "Esthesioneuroblastoma", "Endoscopic Resection"],
        },
        {
            "name": "Dr. Ian Loh",
            "region": "Singapore",
            "title": "ENT Surgeon",
            "experience_years": 15,
            "city": "Singapore",
            "country": "Singapore",
            "institution": "SGH",
            "specialties": ["ENT Surgery", "Sinonasal Tumors", "Minimally Invasive Surgery"],
        },
        {
            "name": "Prof. Daniele Marchioni",
            "region": "Europe",
            "title": "ENT Surgeon",
            "experience_years": 20,
            "city": "Verona",
            "country": "Italy",
            "institution": "University of Verona",
            "specialties": ["ENT Surgery", "Esthesioneuroblastoma", "Endoscopic Endonasal Approach"],
        },
        {
            "name": "Dr. G. K. Rath",
            "region": "India",
            "title": "Radiation Oncologist",
            "experience_years": 40,
            "city": "New Delhi",
            "country": "India",
            "institution": "AIIMS (former)",
            "specialties": ["Radiation Oncology", "Esthesioneuroblastoma", "IMRT"],
        },
    ],
    "Appendiceal Carcinoma": [
        {
            "name": "Dr. Muhammad M. Sardi",
            "region": "USA",
            "title": "Surgical Oncologist",
            "experience_years": 30,
            "city": "Baltimore",
            "country": "USA",
            "institution": "Mercy Medical Center",
            "specialties": ["Surgical Oncology", "Appendiceal Cancer", "CRS+HIPEC"],
        },
        {
            "name": "Dr. Tan Ker Kan",
            "region": "Singapore",
            "title": "Surgical Oncologist",
            "experience_years": 15,
            "city": "Singapore",
            "country": "Singapore",
            "institution": "NUH",
            "specialties": ["Surgical Oncology", "Appendiceal Tumors", "CRS+HIPEC"],
        },
        {
            "name": "Prof. Norman Carr",
            "region": "Europe",
            "title": "Gastrointestinal Oncologist",
            "experience_years": 25,
            "city": "Basingstoke",
            "country": "United Kingdom",
            "institution": "Basingstoke Hospital",
            "specialties": ["GI Oncology", "Peritoneal Malignancy", "Appendix Tumors"],
        },
        {
            "name": "Dr. Anil Heroor",
            "region": "India",
            "title": "Surgical Oncologist",
            "experience_years": 20,
            "city": "Mumbai",
            "country": "India",
            "institution": "Private Practice",
            "specialties": ["Surgical Oncology", "HIPEC", "Appendiceal Mucinous Carcinoma"],
        },
    ],
    "Angioimmunoblastic T-cell Lymphoma (AITL)": [
        {
            "name": "Dr. Steven M. Horwitz",
            "region": "USA",
            "title": "Medical Oncologist",
            "experience_years": 20,
            "city": "New York",
            "country": "USA",
            "institution": "MSKCC",
            "specialties": ["T-cell Lymphomas", "AITL", "Novel Therapies"],
        },
        {
            "name": "Dr. Francesca Lim",
            "region": "Singapore",
            "title": "Hematologist",
            "experience_years": 20,
            "city": "Singapore",
            "country": "Singapore",
            "institution": "SGH",
            "specialties": ["Hematology", "AITL", "Combined Chemo-immunotherapy"],
        },
        {
            "name": "Prof. Ulrich Jäger",
            "region": "Europe",
            "title": "Hematologist",
            "experience_years": 30,
            "city": "Vienna",
            "country": "Austria",
            "institution": "Medical University of Vienna",
            "specialties": ["Hematology", "AITL Trials", "Treatment Guidelines"],
        },
        {
            "name": "Dr. Reena Nair",
            "region": "India",
            "title": "Hematologist",
            "experience_years": 25,
            "city": "Kolkata",
            "country": "India",
            "institution": "TMC",
            "specialties": ["Hematology", "AITL", "Novel Agents"],
        },
    ],
    "Cholangiocarcinoma": [
        {
            "name": "Dr. Ghassan K. Abou-Alfa",
            "region": "USA",
            "title": "Medical Oncologist",
            "experience_years": 25,
            "city": "New York",
            "country": "USA",
            "institution": "MSKCC",
            "specialties": ["Hepatobiliary Oncology", "Cholangiocarcinoma", "FGFR/IDH Inhibitors"],
        },
        {
            "name": "Dr. Joanne Ngeow",
            "region": "Singapore",
            "title": "Medical Oncologist",
            "experience_years": 15,
            "city": "Singapore",
            "country": "Singapore",
            "institution": "NCCS",
            "specialties": ["Medical Oncology", "Biliary Tract Cancers", "Precision Oncology"],
        },
        {
            "name": "Prof. Juan Valle",
            "region": "Europe",
            "title": "Medical Oncologist",
            "experience_years": 20,
            "city": "Manchester",
            "country": "United Kingdom",
            "institution": "The Christie",
            "specialties": ["Medical Oncology", "Cholangiocarcinoma", "ABC Trials"],
        },
        {
            "name": "Dr. Amit Jain",
            "region": "India",
            "title": "HPB Surgeon",
            "experience_years": 15,
            "city": "New Delhi",
            "country": "India",
            "institution": "ILBS",
            "specialties": ["HPB Surgery", "Cholangiocarcinoma", "Curative Resections"],
        },
    ],
    "Gestational Trophoblastic Neoplasia": [
        {
            "name": "Dr. Neil Horowitz",
            "region": "USA",
            "title": "Director of Clinical Research in Gynecologic Oncology",
            "experience_years": 20,
            "city": "Boston",
            "country": "USA",
            "institution": "Dana-Farber Cancer Institute",
            "specialties": ["Gynecologic Oncology", "GTN", "Trophoblastic Disease Center"],
        },
        {
            "name": "Dr. Ann Tan",
            "region": "Singapore",
            "title": "Senior Consultant OBGYN",
            "experience_years": 30,
            "city": "Singapore",
            "country": "Singapore",
            "institution": "Mount Elizabeth",
            "specialties": ["OBGYN", "Molar Pregnancies", "GTN"],
        },
        {
            "name": "Prof. Michael J. Seckl",
            "region": "Europe",
            "title": "Medical Oncologist",
            "experience_years": 25,
            "city": "London",
            "country": "United Kingdom",
            "institution": "Charing Cross Trophoblast Center",
            "specialties": ["Medical Oncology", "GTN", "Clinical Trials"],
        },
        {
            "name": "Dr. Niranjan Chavan",
            "region": "India",
            "title": "Gynecologic Oncologist",
            "experience_years": 20,
            "city": "Mumbai",
            "country": "India",
            "institution": "King Edward Memorial Hospital",
            "specialties": ["Gynecologic Oncology", "High-risk GTN", "Combination Chemotherapy"],
        },
    ],
    "Thymic Carcinoma": [
        {
            "name": "Dr. Giuseppe Giaccone",
            "region": "USA",
            "title": "Medical Oncologist",
            "experience_years": 30,
            "city": "Washington, DC",
            "country": "USA",
            "institution": "Georgetown University (formerly NCI)",
            "specialties": ["Medical Oncology", "Thymic Malignancies", "Global Trials"],
        },
        {
            "name": "Dr. Toh Han Chong",
            "region": "Singapore",
            "title": "Medical Oncologist",
            "experience_years": 25,
            "city": "Singapore",
            "country": "Singapore",
            "institution": "NCCS",
            "specialties": ["Medical Oncology", "Thymic Carcinoma", "Targeted Agents"],
        },
        {
            "name": "Prof. Luciano Mariani",
            "region": "Europe",
            "title": "Thoracic Surgeon",
            "experience_years": 20,
            "city": "Rome",
            "country": "Italy",
            "institution": "Regina Elena Institute",
            "specialties": ["Thoracic Surgery", "Thymic Carcinoma", "Extensive Resections"],
        },
        {
            "name": "Dr. Raja Sundaram",
            "region": "India",
            "title": "Surgical Oncologist",
            "experience_years": 30,
            "city": "Chennai",
            "country": "India",
            "institution": "Apollo Hospitals",
            "specialties": ["Surgical Oncology", "Thymic Tumor Resection", "Thymoma Teams"],
        },
    ],
    "Gastrointestinal Stromal Tumor (GIST)": [
        {
            "name": "Dr. George D. Demetri",
            "region": "USA",
            "title": "Medical Oncologist",
            "experience_years": 30,
            "city": "Boston",
            "country": "USA",
            "institution": "Dana-Farber",
            "specialties": ["Medical Oncology", "GIST", "Imatinib Pioneer"],
        },
        {
            "name": "Dr. Wong Seng Weng",
            "region": "Singapore",
            "title": "Medical Oncologist",
            "experience_years": 20,
            "city": "Singapore",
            "country": "Singapore",
            "institution": "Parkway Cancer Centre",
            "specialties": ["Medical Oncology", "GIST", "TKIs"],
        },
        {
            "name": "Prof. Peter Reichardt",
            "region": "Europe",
            "title": "Oncologist",
            "experience_years": 25,
            "city": "Berlin",
            "country": "Germany",
            "institution": "HELIOS Clinic",
            "specialties": ["Sarcoma Oncology", "GIST Studies", "EORTC"],
        },
        {
            "name": "Dr. Rajiv Agarwal",
            "region": "India",
            "title": "Medical Oncologist",
            "experience_years": 20,
            "city": "Mumbai",
            "country": "India",
            "institution": "Tata Memorial",
            "specialties": ["Medical Oncology", "GIST", "Imatinib"],
        },
    ],
    "Pancreatic Neuroendocrine Tumors (pNETs)": [
        {
            "name": "Dr. James Yao",
            "region": "USA",
            "title": "Medical Oncologist",
            "experience_years": 20,
            "city": "Houston",
            "country": "USA",
            "institution": "MD Anderson",
            "specialties": ["Medical Oncology", "Neuroendocrine Tumors", "Everolimus/Sunitinib"],
        },
        {
            "name": "Dr. Thng Choon Hua",
            "region": "Singapore",
            "title": "Endocrinologist",
            "experience_years": 15,
            "city": "Singapore",
            "country": "Singapore",
            "institution": "SGH",
            "specialties": ["Endocrinology", "pNETs", "SSA Therapy/PRRT"],
        },
        {
            "name": "Prof. Kjell Öberg",
            "region": "Europe",
            "title": "Endocrine Oncologist",
            "experience_years": 40,
            "city": "Uppsala",
            "country": "Sweden",
            "institution": "Uppsala University",
            "specialties": ["Endocrine Oncology", "NETs", "ENETS Guidelines"],
        },
        {
            "name": "Dr. C. S. Pramesh",
            "region": "India",
            "title": "GI Surgical Oncologist, Director",
            "experience_years": 25,
            "city": "Mumbai",
            "country": "India",
            "institution": "Tata Memorial",
            "specialties": ["GI Surgical Oncology", "Pancreas Surgery", "pNETs"],
        },
    ],
    "Penile Squamous Cell Carcinoma": [
        {
            "name": "Dr. Philippe E. Spiess",
            "region": "USA",
            "title": "Urologic Oncologist",
            "experience_years": 15,
            "city": "Tampa",
            "country": "USA",
            "institution": "Moffitt Cancer Center",
            "specialties": ["Urologic Oncology", "Penile Cancer", "Nodal Dissection"],
        },
        {
            "name": "Dr. Tan Teing Ee",
            "region": "Singapore",
            "title": "Urologist",
            "experience_years": 20,
            "city": "Singapore",
            "country": "Singapore",
            "institution": "SGH",
            "specialties": ["Urology", "Penile Cancer", "Penectomy"],
        },
        {
            "name": "Prof. Henk van der Poel",
            "region": "Europe",
            "title": "Urologic Oncologist",
            "experience_years": 25,
            "city": "Amsterdam",
            "country": "Netherlands",
            "institution": "Netherlands Cancer Institute",
            "specialties": ["Urologic Oncology", "Penile Sparing Techniques", "Sentinel Node"],
        },
        {
            "name": "Dr. Anup Kumar",
            "region": "India",
            "title": "Urologic Oncologist",
            "experience_years": 20,
            "city": "New Delhi",
            "country": "India",
            "institution": "Safdarjung Hospital",
            "specialties": ["Urologic Oncology", "Penile Cancer Surgery", "Reconstructive Techniques"],
        },
    ],
    "Vulvar Cancer": [
        {
            "name": "Dr. Kathleen M. Schmeler",
            "region": "USA",
            "title": "Gynecologic Oncologist",
            "experience_years": 15,
            "city": "Houston",
            "country": "USA",
            "institution": "MD Anderson",
            "specialties": ["Gynecologic Oncology", "Vulvar Cancer", "Sentinel Node Dissection"],
        },
        {
            "name": "Dr. See Tho Kai Yin",
            "region": "Singapore",
            "title": "Senior Gynecologic Oncologist",
            "experience_years": 30,
            "city": "Singapore",
            "country": "Singapore",
            "institution": "KKH",
            "specialties": ["Gynecologic Oncology", "Vulvar Cancer", "Combined Modality"],
        },
        {
            "name": "Prof. Lukas J. Bamberg",
            "region": "Europe",
            "title": "Gynecologic Oncologist",
            "experience_years": 20,
            "city": "Berlin",
            "country": "Germany",
            "institution": "Charité Berlin",
            "specialties": ["Gynecologic Oncology", "Vulvar Reconstructive Surgery", "Radical Excision"],
        },
        {
            "name": "Dr. Amita Maheshwari",
            "region": "India",
            "title": "Professor & Head, Gyne-Oncology",
            "experience_years": 30,
            "city": "Mumbai",
            "country": "India",
            "institution": "Tata Memorial Hospital",
            "specialties": ["Gynecologic Oncology", "Vulvar Cancer", "Women's Cancer Center"],
        },
    ],
    "Vaginal Cancer": [
        {
            "name": "Dr. Sarah M. Temkin",
            "region": "USA",
            "title": "Gynecologic Oncologist",
            "experience_years": 20,
            "city": "Cleveland",
            "country": "USA",
            "institution": "Case Western/Seidman Cancer Center",
            "specialties": ["Gynecologic Oncology", "Vaginal Cancer", "Brachytherapy"],
        },
        {
            "name": "Dr. Lim Lay Hoon",
            "region": "Singapore",
            "title": "Radiation Oncologist",
            "experience_years": 15,
            "city": "Singapore",
            "country": "Singapore",
            "institution": "NCIS",
            "specialties": ["Radiation Oncology", "Gynecologic Brachytherapy", "Interstitial Implants"],
        },
        {
            "name": "Prof. Ignace Vergote",
            "region": "Europe",
            "title": "Gynecologic Oncologist",
            "experience_years": 35,
            "city": "Leuven",
            "country": "Belgium",
            "institution": "University Hospital Leuven",
            "specialties": ["Gynecologic Oncology", "Rare Vaginal Cancers", "European Guidelines"],
        },
        {
            "name": "Dr. Swapna Misra",
            "region": "India",
            "title": "Gynecologic Oncologist",
            "experience_years": 20,
            "city": "Mumbai",
            "country": "India",
            "institution": "KEM Hospital",
            "specialties": ["Gynecologic Oncology", "Vaginal Cancer", "Multidisciplinary Care"],
        },
    ],
    "Osteosarcoma": [
        {
            "name": "Dr. Richard Gorlick",
            "region": "USA",
            "title": "Division Head of Pediatrics, Director of Osteosarcoma Research Laboratory",
            "experience_years": 25,
            "city": "Houston",
            "country": "USA",
            "institution": "MD Anderson Cancer Center",
            "specialties": ["Pediatric Oncology", "Osteosarcoma", "Osteosarcoma Research"],
        },
        {
            "name": "Dr. Paul A. Meyers",
            "region": "USA",
            "title": "Pediatric Oncologist",
            "experience_years": 40,
            "city": "New York",
            "country": "USA",
            "institution": "MSKCC",
            "specialties": ["Pediatric Oncology", "Osteosarcoma", "Chemotherapy Protocols"],
        },
        {
            "name": "Dr. Kam Chan Hui",
            "region": "Singapore",
            "title": "Pediatric Oncologist",
            "experience_years": 15,
            "city": "Singapore",
            "country": "Singapore",
            "institution": "KKH",
            "specialties": ["Pediatric Oncology", "Osteosarcoma", "MAP Chemotherapy"],
        },
        {
            "name": "Prof. Stefan Bielack",
            "region": "Europe",
            "title": "Pediatric Oncologist",
            "experience_years": 30,
            "city": "Stuttgart",
            "country": "Germany",
            "institution": "Olgahospital",
            "specialties": ["Pediatric Oncology", "Osteosarcoma", "COSS Trials"],
        },
        {
            "name": "Dr. G. K. Prabhu",
            "region": "India",
            "title": "Orthopedic Oncologist",
            "experience_years": 20,
            "city": "Bengaluru",
            "country": "India",
            "institution": "HCG",
            "specialties": ["Orthopedic Oncology", "Limb-sparing Surgery", "Osteosarcoma"],
        },
    ],
    "Ewing Sarcoma": [
        {
            "name": "Dr. Leonard Wexler",
            "region": "USA",
            "title": "Pediatric Oncologist",
            "experience_years": 35,
            "city": "New York",
            "country": "USA",
            "institution": "MSKCC",
            "specialties": ["Pediatric Oncology", "Ewing Sarcoma", "INT-0091 Trials"],
        },
        {
            "name": "Dr. Viulnerability Liu",
            "region": "Singapore",
            "title": "Pediatric Oncologist",
            "experience_years": 10,
            "city": "Singapore",
            "country": "Singapore",
            "institution": "NUH",
            "specialties": ["Pediatric Oncology", "Ewing Sarcoma", "VIDE/VAI Chemotherapy"],
        },
        {
            "name": "Prof. Theodoros Grünewald",
            "region": "Europe",
            "title": "Oncologist",
            "experience_years": 15,
            "city": "Essen",
            "country": "Germany",
            "institution": "University Hospital Essen",
            "specialties": ["Oncology", "Ewing Sarcoma Biology", "Euro-E.W.I.N.G."],
        },
        {
            "name": "Dr. Santanu Sen",
            "region": "India",
            "title": "Pediatric Oncologist",
            "experience_years": 20,
            "city": "Kolkata",
            "country": "India",
            "institution": "Private Practice",
            "specialties": ["Pediatric Oncology", "Ewing Sarcoma", "Cooperative Protocols"],
        },
    ],
    "Retinoblastoma": [
        {
            "name": "Dr. Jesse L. Berry",
            "region": "USA",
            "title": "Ocular Oncologist",
            "experience_years": 10,
            "city": "Los Angeles",
            "country": "USA",
            "institution": "Children's Hospital LA",
            "specialties": ["Ocular Oncology", "Retinoblastoma", "Intra-arterial Chemotherapy"],
        },
        {
            "name": "Dr. Audrey Chia",
            "region": "Singapore",
            "title": "Senior Pediatric Ophthalmologist",
            "experience_years": 20,
            "city": "Singapore",
            "country": "Singapore",
            "institution": "SNEC",
            "specialties": ["Pediatric Ophthalmology", "Retinoblastoma", "Chemoreduction"],
        },
        {
            "name": "Prof. David H. Abramson",
            "region": "Europe",
            "title": "Ocular Oncologist",
            "experience_years": 40,
            "city": "New York",
            "country": "USA",
            "institution": "MSKCC",
            "specialties": ["Ocular Oncology", "Retinoblastoma", "Local Therapies"],
        },
        {
            "name": "Dr. Bikramjit Pal",
            "region": "India",
            "title": "Ocular Oncologist",
            "experience_years": 15,
            "city": "Chennai",
            "country": "India",
            "institution": "Sankara Nethralaya",
            "specialties": ["Ocular Oncology", "Retinoblastoma", "Globe-conserving Treatment"],
        },
    ],
    "Malignant Mesothelioma": [
        {
            "name": "Dr. Hedy Lee Kindler",
            "region": "USA",
            "title": "Medical Oncologist",
            "experience_years": 25,
            "city": "Chicago",
            "country": "USA",
            "institution": "University of Chicago",
            "specialties": ["Medical Oncology", "Mesothelioma", "Pemetrexed Trials"],
        },
        {
            "name": "Dr. Vyas Prasad",
            "region": "Singapore",
            "title": "Thoracic Surgeon",
            "experience_years": 20,
            "city": "Singapore",
            "country": "Singapore",
            "institution": "NCID/NCCS",
            "specialties": ["Thoracic Surgery", "Mesothelioma", "Extrapleural Pneumonectomy"],
        },
        {
            "name": "Prof. Marc de Perrot",
            "region": "Europe",
            "title": "Thoracic Surgeon",
            "experience_years": 20,
            "city": "Toronto",
            "country": "Canada",
            "institution": "Toronto General Hospital",
            "specialties": ["Thoracic Surgery", "Mesothelioma Surgery", "Immunotherapy"],
        },
        {
            "name": "Dr. S. Vijayakumar",
            "region": "India",
            "title": "Medical Oncologist",
            "experience_years": 15,
            "city": "Chennai",
            "country": "India",
            "institution": "Apollo Specialty",
            "specialties": ["Medical Oncology", "Mesothelioma", "Multi-modality Treatment"],
        },
    ],
    "Cancer of Unknown Primary (CUP)": [
        {
            "name": "Dr. Anthony Greco",
            "region": "USA",
            "title": "Medical Oncologist",
            "experience_years": 45,
            "city": "Nashville",
            "country": "USA",
            "institution": "Sarah Cannon Research Institute",
            "specialties": ["Medical Oncology", "CUP", "Empiric Chemotherapy"],
        },
        {
            "name": "Dr. Ravindran Kanesvaran",
            "region": "Singapore",
            "title": "Medical Oncologist",
            "experience_years": 15,
            "city": "Singapore",
            "country": "Singapore",
            "institution": "NCCS",
            "specialties": ["Medical Oncology", "CUP Service", "Molecular Profiling"],
        },
        {
            "name": "Prof. Fizazi Karim",
            "region": "Europe",
            "title": "Medical Oncologist",
            "experience_years": 20,
            "city": "Villejuif",
            "country": "France",
            "institution": "Gustave Roussy",
            "specialties": ["Medical Oncology", "CUP Trials", "ESMO Guidelines"],
        },
        {
            "name": "Dr. Harit Chaturvedi",
            "region": "India",
            "title": "Surgical Oncologist",
            "experience_years": 30,
            "city": "Delhi",
            "country": "India",
            "institution": "Max Healthcare",
            "specialties": ["Surgical Oncology", "CUP", "Treatable Subsets"],
        },
    ],
}

